apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: realtimeapp-spc # keep -spc suffix
  namespace: realtimeapp
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-BIDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BIDB_USERNAME-alias        
          - path: password
            objectAlias: BIDB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-DSDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DSDB_USERNAME-alias        
          - path: password
            objectAlias: DSDB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-DSLIODB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DSLIODB_USERNAME-alias        
          - path: password
            objectAlias: DSLIODB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-OPERATIONALDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: OPERATIONALDB_USERNAME-alias        
          - path: password
            objectAlias: OPERATIONALDB_PASSWORD-alias

      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-AIML"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: KAFKA_USERNAME-alias        
          - path: password
            objectAlias: KAFKA_PASSWORD-alias
  secretObjects:
    - data:
        - key: BIDB_USERNAME
          objectName: BIDB_USERNAME-alias
        - key: BIDB_PASSWORD
          objectName: BIDB_PASSWORD-alias

        - key: DSDB_USERNAME
          objectName: DSDB_USERNAME-alias 
        - key: DSDB_PASSWORD
          objectName: DSDB_PASSWORD-alias
        
        - key: DSLIODB_USERNAME
          objectName: DSLIODB_USERNAME-alias
        - key: DSLIODB_PASSWORD
          objectName: DSLIODB_PASSWORD-alias

        - key: OPERATIONALDB_USERNAME
          objectName: OPERATIONALDB_USERNAME-alias
        - key: OPERATIONALDB_PASSWORD  
          objectName: OPERATIONALDB_PASSWORD-alias
          
        - key: KAFKA_PASSWORD
          objectName: KAFKA_PASSWORD-alias
        - key: KAFKA_USERNAME
          objectName: KAFKA_USERNAME-alias
      secretName: aws-secrets-manager-secret
      type: Opaque