replicaCount: 2

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-mtvapi
  tag: 1.2.51
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8084

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 128m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: "/live"
    port: 8084
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/ready"
    port: 8084
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70