image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-mtvapi

extraEnvs:
  - name: MTV_LOGGING_MODE
    value: "console"
  - name: MTV_JDBC_URL
    value: "jdbc:oracle:thin:@prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com:1581/LRD"
  - name: MTV_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_PASSWORD
  - name: LOGIN_SOURCE_NAME
    value: "keycloak"
  - name: WEBCLIENT_URL
    value: "https://lrd-mtvclient.fms.itfs.lta.gov.sg"
  - name: KEYCLOAK_ISSUER_URI_HTTPS
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO"
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: MTV_CLIENT_ID
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: MTV_CLIENT_SECRET
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI
    value: "https://lrd-mtvclient.fms.itfs.lta.gov.sg/lrd-mtvapi/login/oauth2/code/MTV"
  - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO"
  - name: INTROSPECTION_ENDPOINT
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/token/introspect"
  - name: TOKEN_ENDPOINT
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/token"
  - name: LOGOUT_ENDPOINT
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/logout"
  - name: TZ
    value: "Asia/Singapore"
  - name: OTLP_SERVICE_NAME
    value: "LRD_MTV_API"
  - name: PROPERTY_OTLP_COLLECTOR_URL
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: MTV_isAcCodeAmendmentFeatureEnabled
    value: "1"
  - name: MTV_menu.map.report.fieldstrength
    value: "0"
  - name: MTV_menu.ostv
    value: "1"
  - name: MTV_menu.fleetanalysis
    value: "0"
  - name: MTV_menu.actionlog
    value: "1"
  - name: MTV_menu.mileage.summary
    value: "1"
  - name: MTV_menu.package
    value: "1"
  - name: MTV_menu.mark.itp
    value: "1"
  - name: MTV_menu.mark.flbp
    value: "1"
  - name: MTV_menu.taskscheduler
    value: "1"
  - name: MTV_menu.auto.coding
    value: "1"
  - name: MTV_menu.period
    value: "0"
  - name: MTV_menu.week
    value: "0"
  - name: MTV_menu.calendar
    value: "0"
  - name: MTV_menu.routemapping
    value: "0"
  - name: MTV_menu.routegroup
    value: "0"
  - name: MTV_menu.mws
    value: "0"
  - name: MTV_menu.mas
    value: "0"
  - name: MTV_menu.mileagedaytype
    value: "0"
  - name: MTV_menu.contract
    value: "1"
  - name: MTV_menu.contractFinalization
    value: "1"
  - name: MTV_menu.mapviewenable
    value: "0"
  - name: MTV_menu.areaanalysis
    value: "0"
  - name: MTV_menu.safanalysis
    value: "0"
  - name: MTV_menu.config
    value: "1"
  - name: MTV_menu.pj
    value: "1"
  - name: MTV_menu.trip.analysis
    value: "2"
  - name: MTV_menu.area.summary
    value: "0"
  - name: MTV_menu.pinch
    value: "0"
  - name: MTV_menu.operational
    value: "0"
  - name: MTV_menu.system.reports
    value: "0"
  - name: MTV_customerName
    value: "LTA"
  - name: MTV_menu.flbp.exclusion
    value: "1"
  - name: MTV_OTELENABLED
    value: "0"
  - name: MTV_menu.mileageappeal
    value: "1"
  - name: MTV_menu.telltalevisualizer
    value: "0"
  - name: MTV_menu.timetable
    value: "0"
  - name: MTV_menu.contactcentre
    value: "0"
  - name: MTV_exclusionFromFileEnabled
    value: "1"
  - name: MTV_FLBP_WORKSHEET_LOCATION
    value: "/san/mtv_excel_templates"
  - name: MTV_EXCLUSION_WORKSHEET_LOCATION
    value: "/san/mtv_excel_templates"
  - name: "THREAD_STALL_THRESHOLD_SECS"
    value: "600"
  - name: "NATS_ALERT_INTERVAL_MINUTES"
    value: "10"
  - name: NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: MEMORY_THRESHOLD_MB
    value: "600"
  - name: NATS_URL
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: KEYCLOAK_BASE_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO"

serviceAccount:
  create: true
  name: lrd-mtvapi-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-LRD

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-mtvapi-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-mtvapi-san-fsx-pv
  
extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-mtvapi-san-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-mtvapi-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/ready"
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-mtvapi.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-mtvapi.fms.itfs.lta.gov.sg
      secretName: lrd-mtvapi-tls
