extraEnvs:
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_USERNAME
    value: "can-telltale"
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: VEHICLE_STATIC_DATA_ENDPOINT
    value: "https://lrd-cache.fms-uat.itfs.lta.gov.sg/v1"
  - name: NATS_BROKER_URL
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: KAFKA_CONSUMER_TELLTALE_TOPIC  
    value: "telltale.nta.app.ingest-telltale.1"
  - name: NATS_ALERT_TOPIC
    value: "CAN.Alerts.Alert" 
  - name: APPLICATION_ENV
    value: "uat" 
  - name: TZ
    value: "Asia/Singapore"  

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/success-codes: "200,302"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: can-telltale.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - can-telltale.fms-uat.itfs.lta.gov.sg
      secretName: can-telltale-tls

serviceAccount:
  create: true
  name: can-telltale-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-CAN-TELLTALE
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "can-telltale-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

keda:
  enabled: true
  secret:
    existingSecret: "aws-secrets-manager-secret"
    usernameKey: "username"
    passwordKey: "password"
    sasl: "scram_sha512"
    tls: "enable"
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
          consumerGroup: "canconsumer"
          topic: "telltale.nta.app.ingest-telltale.1"
          lagThreshold: "5000"