apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rtvehicleprediction-spc # keep -spc suffix
  namespace: rtvehicleprediction
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-AIML"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: KAFKA_USERNAME-alias        
          - path: password
            objectAlias: KAFKA_PASSWORD-alias
  secretObjects:
    - data:
        - key: KAFKA_PASSWORD
          objectName: KAFKA_PASSWORD-alias
        - key: KAFKA_USERNAME
          objectName: KAFKA_USERNAME-alias
      secretName: aws-secrets-manager-secret
      type: Opaque