extraEnvs:
  - name: KAFKA_URL
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_TOPIC
    value: "cc_lrd_passages"
  - name: KAFKA_USERNAME_ENV
    value: "realtimeapp"
  - name: KAFKA_PASSWORD_ENV
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: TZ
    value: "Asia/Singapore"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: KAFKA_THRESHOLD_MINUTES
    value: "60"
  - name: MEMORY_THRESHOLD_MB
    value: "600"
  - name: HEARTBEAT_THRESHOLD_MINS 
    value: "10"
  - name: NATS_ALERT_SUBJECT
    value: "NTA_PROD_CLOUD.AIML.Alerts.Alert"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    value: "rtvehicleprediction"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: rtvehicleprediction.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - rtvehicleprediction.fms-uat.itfs.lta.gov.sg
      secretName: rtvehicleprediction-tls

serviceAccount:
  create: true
  name: rtvehicleprediction-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-REALTIMEAPP

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "rtvehicleprediction-spc"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi