extraEnvs:
  - name: DB_SID
    value: "LRD"
  - name: DB_DATABASEMACHINEIP
    value: "uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com"
  - name: DB_BIDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_BIDB_USER
    value: "BIDB"
  - name: DB_BIDB_USER_APP
    value: "BI_BIDB"
  - name: DB_DSDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSDB_USER_APP
    value: "BI_DSDB"
  - name: DB_DSLIODB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSLIODB_USER_APP
    value: "BI_DSLIODB"
  - name: DB_OPERATIONALDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_OPERATIONAL_USER_APP
    value: "BI_OPERATIONALDB"
  - name: DB_PORT
    value: "1581"
  - name: DB_CONNECTION_TIMEOUT
    value: "120"
  - name: DB_DRIVER_NAME
    value: "oracle.jdbc.driver.OracleDriver"
  - name: DB_MAX_ACTIVE_CONNECTIONS
    value: "40"
  - name: DB_MAX_IDLE_CONNECTIONS
    value: "0"
  - name: DB_MAX_WAIT_TIME
    value: "30000"
  - name: ME_NATSSERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: ME_CCUPLOADPROCESSINGPATH
    value: "/san/MainETL/CCRecordings"
  - name: ME_CC_CDPREDDATABASEPATH
    value: ""
  - name: ME_CCSTREAMNAME
    value: "CC_Upload"
  - name: ME_CCFILENAMESUBJECT
    value: "CC_Files"
  - name: CC_OPERATORLOC_1
    value: "/san/MainETL/CCRecordings1, SBST"
  - name: CC_OPERATORLOC_2
    value: "/san/MainETL/CCRecordings2, SMRT"
  - name: CC_OPERATORLOC_3
    value: "/san/MainETL/CCRecordings3, TTS"
  - name: CC_OPERATORLOC_4
    value: "/san/MainETL/CCRecordings4, GAS"
  - name: ME_FILESTOPROCESSFOLDER
    value: "FilesToProcess"
  - name: ME_FILESNOTPROCESSEDFOLDER
    value: "FilesNotProcessed"
  - name: TZ
    value: "Asia/Singapore"
  - name: ME_NATSREPLICAS
    value: "3"
  - name: ME_NATS_RETENTION_MESSAGE_DAYS
    value: "7"
  - name: "ME_THREAD_STALL_THRESHOLD_SECS"
    value: "600"
  - name: ME_NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: ME_MEMORY_THRESHOLD_MB
    value: "300"
  - name: ISLEASEENABLE
    value: "true"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: lrd-ccfilecopyandpublisher
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: lrd-ccfilecopyandpublisher
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: lrd-ccfilecopyandpublisher-sa
        namespace: lrd-ccfilecopyandpublisher
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-ccfilecopyandpublisher-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-ccfilecopyandpublisher-san-fsx-pv
  
serviceAccount:
  create: true
  name: lrd-ccfilecopyandpublisher-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-LRD

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-ccfilecopyandpublisher-san-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-ccfilecopyandpublisher-spc"
      
extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-ccfilecopyandpublisher.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-ccfilecopyandpublisher.fms-uat.itfs.lta.gov.sg
      secretName: lrd-ccfilecopyandpublisher-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
