extraEnvs:
  - name: PREDICTIONPARSER_PREDICTIONPARSERPATH
    value: "/san/Prediction"
  - name: PREDICTIONPARSER_NATSSUBJECT
    value: "dat_files"
  - name: PREDICTIONPARSER_NATSSTREAM
    value: "BIETL-PredictionParser"
  - name: PREDICTIONPARSER_NATSSERVER
    value: "nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: TZ
    value: "Asia/Singapore"
 - name: PREDICTIONPARSER_NATSREPLICAS
    value: "3"
  - name: PREDICTIONPARSER_NATS_RETENTION_MESSAGE_DAYS
    value: "7"
  - name: PREDICTIONPARSER_NATS_ALERT_SUBJECT
    value: "NTA_PROD_CLOUD.LRD.Alerts.Alert"
  - name: PREDICTIONPARSER_DATFILESOURCE
    value: "FILES"
  - name: PREDICTIONPARSER_DATFILESBASEPATH
    value: "/san/Prediction/FilesToProcess"
  - name: PREDICTIONPARSER_FILESTOLOADFOLDER
    value: "FilesToLoad"
  - name: PREDICTIONPARSER_FILESPROCESSEDFOLDER
    value: "FilesProcessed"
  - name: PREDICTIONPARSER_FILESNOTPROCESSEDFOLDER
    value: "FilesNotProcessed"
  - name: PREDICTIONPARSER_LOGPATH
    value: "parserlog"
  - name: PREDICTIONPARSER_CONFIGPATH
    value: "config"
  - name: PREDICTIONPARSER_ISBACKUPENABLE
    value: "FALSE"
  - name: PREDICTIONPARSER_BACKUPLOCATION
    value: "/LRD_Backup"
  - name: PREDICTIONPARSER_SERIAL
    value: "0"
  - name: PREDICTIONPARSER_PARALLEL
    value: "1"
  - name: PREDICTIONPARSER_NUMBEROFBANDS
    value: "2"
  - name: PREDICTIONPARSER_LOADRAWDATA
    value: "TRUE"
  - name: PREDICTIONPARSER_BANDLOWERRANGE_1
    value: "0"
  - name: PREDICTIONPARSER_BANDUPPERRANGE_1
    value: "300"
  - name: PREDICTIONPARSER_BANDACCURACY_1
    value: "180"
  - name: PREDICTIONPARSER_BANDLOWERRANGE_2
    value: "300"
  - name: PREDICTIONPARSER_BANDUPPERRANGE_2
    value: "600"
  - name: PREDICTIONPARSER_BANDACCURACY_2
    value: "300"
  - name: PREDICTIONPARSER_FSX_CHECK_INTERVAL_MINS
    value: "5"
  - name: PREDICTIONPARSER_THREAD_STALL_THRESHOLD_SECS
    value: "600"
  - name: PREDICTIONPARSER_MEMORY_THRESHOLD_MB
    value: "4500"
  - name: LOG_LEVEL
    value: "info"
  - name: PREDICTIONPARSER_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: PREDICTIONPARSER_POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace   
 
extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-predictionparser-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-predictionparser-san-fsx-pv
  
extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-predictionparser-san-fsx-pvc

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-predictionparser.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-predictionparser.fms-uat.itfs.lta.gov.sg
      secretName: lrd-predictionparser-tls