extraEnvs:
  - name: DB_SID
    value: "LRD"
  - name: DB_DATABASEMACHINEIP
    value: "uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com"
  - name: DB_BIDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_BIDB_USER
    value: "BIDB"
  - name: DB_BIDB_USER_APP
    value: "BI_BIDB"
  - name: DB_DSDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSDB_USER_APP
    value: "BI_DSDB"
  - name: DB_DSLIODB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSLIODB_USER_APP
    value: "BI_DSLIODB"
  - name: DB_OPERATIONALDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_OPERATIONAL_USER_APP
    value: "BI_OPERATIONALDB"
  - name: DB_PORT
    value: "1581"
  - name: DB_CONNECTION_TIMEOUT
    value: "120"
  - name: DB_DRIVER_NAME
    value: "oracle.jdbc.driver.OracleDriver"
  - name: DB_MAX_ACTIVE_CONNECTIONS
    value: "40"
  - name: DB_MAX_IDLE_CONNECTIONS
    value: "0"
  - name: DB_MAX_WAIT_TIME
    value: "30000"
  - name: ME_NATSSERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: ME_EXPORTSTREAMNAME
    value: "BIExport"
  - name: ME_FASTREAMNAME
    value: "FleetAnalyser"
  - name: ME_EXPORTROUTESUBJECT
    value: "RouteId"
  - name: ME_FATECHVEHNOSUBJECT
    value: "TechnicalVehicleNumber"
  - name: ME_EXPORTTABLENAME_1
    value: "SCHEMA=BIDB, TABLE=SA_STOPPOINTS, RECIPIENT=ALL, DAY_TYPE=processday , FROM=sysdate-10h, TO=sysdate, PREFIX=DFYYYYMMdd_, FILENAME=, SUFFIX=SA_STOPPOINTS, COLHEADER=true, FHEADER=false, FFOOTER=false, EXPORT_MODE=route, EXPORT_TYPE=Stops"
  - name: ME_EXPORTTABLENAME_2
    value: "SCHEMA=BIDB, TABLE=SA_TRIPS, RECIPIENT=ALL, DAY_TYPE=processday , FROM=sysdate-10h, TO=sysdate, PREFIX=DFYYYYMMdd_, FILENAME=, SUFFIX=SA_TRIPS, COLHEADER=true, FHEADER=false, FFOOTER=false, EXPORT_MODE=route, EXPORT_TYPE=Trips"
  - name: ME_EXPORTTABLENAME_3
    value: "SCHEMA=BIDB, TABLE=DOOREVENTS, RECIPIENT=ALL, DAY_TYPE=processday , FROM=sysdate-10h, TO=sysdate, PREFIX=DFYYYYMMdd_, FILENAME= DOOREVENTS, SUFFIX=_TONO_ContractName, COLHEADER=true, FHEADER=false, FFOOTER=false, EXPORT_MODE=route, EXPORT_TYPE=DoorEvents" 
  - name: ME_OPERATOREXPORTPATH_1
    value: "LOCATION=/san/Export/SMRT, SHORT_NAME=SMRT, FILTER=OPERATOR_SHORT_NAME, FILTER_TYPE=VARCHAR"
  - name: ME_OPERATOREXPORTPATH_2
    value: "LOCATION=/san/Export/SBST, SHORT_NAME=SBST, FILTER=OPERATOR_SHORT_NAME, FILTER_TYPE=VARCHAR"
  - name: ME_OPERATOREXPORTPATH_3
    value: "LOCATION=/san/Export/TTS, SHORT_NAME=TTS, FILTER=OPERATOR_SHORT_NAME, FILTER_TYPE=VARCHAR"
  - name: ME_OPERATOREXPORTPATH_4
    value: "LOCATION=/san/Export/GAS, SHORT_NAME=GAS, FILTER=OPERATOR_SHORT_NAME, FILTER_TYPE=VARCHAR"
  - name: ME_OPERATOREXPORTPATH_5
    value: "LOCATION=/san/Export/LTA, SHORT_NAME=LTA, FILTER=NONE, FILTER_TYPE=NONE"
  - name: ME_OPERATOREXPORTPATH_6
    value: "LOCATION=/LRD_Backup/NGAVL_EXPORT/NTA_BIDA, SHORT_NAME=NTA, FILTER=NONE, FILTER_TYPE=NONE" 
  - name: ME_EXPORTTYPEDAYTYPE_1
    value: "EXPORTTYPE=route, DAYTYPE=processday, FROM=sysdate-10h, TO=sysdate"
  - name: ME_EXPORTTYPEDAYTYPE_2
    value: "EXPORTTYPE=vehicle, DAYTYPE=calendarday, FROM=sysdate-1d, TO=sysdate"
  - name: ME_ISSINGLEFILEEXPORT
    value: "true"
  - name: ME_FOLDERWISEEXPORTENABLE
    value: "false"
  - name: TZ
    value: "Asia/Singapore"
  - name: ME_NATSREPLICAS
    value: "3"
  - name: ME_NATS_RETENTION_MESSAGE_DAYS
    value: "7"
  - name: ME_SP_STOPQUALITY_1
    value: STAGINGDB.P_STOPPOSITIONQUALITYDAY
  - name: ME_SP_STOPQUALITY_2
    value: BIDB.BIDB_MAIN.p_LoadstoppointData
  - name: ME_SP_STOPQUALITY_3_1
    value: BIDB.BIDB_MAIN.p_runstoppointCorrection_1
  - name: ME_SP_STOPQUALITY_3_2
    value: BIDB.BIDB_MAIN.p_runstoppointCorrection_2
  - name: ME_SP_STOPQUALITY_3_3
    value: BIDB.BIDB_MAIN.p_runstoppointCorrection_3
  - name: ME_SP_STOPQUALITY_3_4
    value: BIDB.BIDB_MAIN.p_runstoppointCorrection_4
  - name: ME_SP_STOPQUALITY_4
    value: BIDB.BIDB_MAIN.p_runStopCorrNQualityBVProcs
  - name: ME_DATAEXPORTPROCESSINGPATH
    value: "/san/MainETL/DataExportProcessing"
  - name: "THREAD_STALL_THRESHOLD_SECS"
    value: "600"
  - name: NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: MEMORY_THRESHOLD_MB
    value: "300"
  - name: ISLEASEENABLE
    value: "true"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: ME_TCCASUBJECTNAME
    value: "TccaOperatorDetails"
  - name: ME_TCCASTREAMNAME
    value: "TccaOperator"

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: lrd-poststagingeventpublisher
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: lrd-poststagingeventpublisher
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: lrd-poststagingeventpublisher-sa
        namespace: lrd-poststagingeventpublisher

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-poststagingeventpublisher.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-poststagingeventpublisher.fms-uat.itfs.lta.gov.sg
      secretName: lrd-poststagingeventpublisher-tls

serviceAccount:
  create: true
  name: lrd-poststagingeventpublisher-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-LRD

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-poststagingeventpublisher-spc"
    
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
