image:
  repository:  381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/liodata-scheduler
  tag: 1.0.23
  
extraEnvs:
  - name: LIODATA_SCHEDULER_CUSTOMERNAME
    value: "LTA"
  - name: NATS_URL
    value: "nats.fms-uat.itfs.lta.gov.sg"
  - name: NATS_PORT
    value: "4222"
  - name: LIODATA_SCHEDULER_SUBJECT
    value: "LioData.Nats.Messaging.UI.QueueBased_LTA"
  - name: LLIODATA_SCHEDULER_QUEUE
    value: "QueueConnectorNew_LTA"
  - name: LIODATA_SCHEDULER_SUBJECTCHILD
    value: "LioData.Nats.Messaging.UI.QueueChildBased_LTA"
  - name: LIODATA_SCHEDULER_QUEUECHILD
    value: "QueueChildConnectorNew_LTA"
  - name: LIODATA_SCHEDULER_VERSION
    value: "000DF300"
  - name: RDS_PRODSERVICE_NAME
    value: "LIODATA"
  - name: RDS_ADMINSERVICENAME
    value: "LIODATA"
  - name: RDS_ENDPOINT
    value: "uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com"
  - name: RDS_PORT
    value: "1581"
  - name: RDS_PDB_NAME
    value: "LIODATA,LIODATA"
  # - name: LIODATA_SCHEDULER_OSMSERVER
  #   value: "nta-test2-rds-oracle.cx0xnozkkowx.eu-west-1.rds.amazonaws.com"
  # - name: LIODATA_SCHEDULER_GINIPATH
  #   value: "dvs_ld11.ini"
  - name: LIODATA_RELOAD_SUBJECT
    value: "LioData.Nats.Messaging.UI.ReloadSubject_LTA"
  - name: TZ
    value: "Asia/Singapore"
  - name: LIODATA_CONSUMER_LIODATAALERTS
    value: "CustomerName_PROD_CLOUD.LioData.Alerts.Alert"
  - name: LIODATA_LOGGINGTYPE
    value: "all"
  - name: RDS_LIODATA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LIODATA_PASSWORD
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: liodata-scheduler
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: liodata-scheduler
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: liodata-scheduler-sa
        namespace: liodata-scheduler

serviceAccount:
  create: true
  name: liodata-scheduler-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-LIODATA

extraVolumes:
 - name: secrets-store-inline
   csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: "liodata-scheduler-spc"

extraVolumeMounts:
 - name: secrets-store-inline
   mountPath: "/mnt/secrets-store"
   readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck/liveness/"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: liodata-scheduler.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - liodata-scheduler.fms-uat.itfs.lta.gov.sg
      secretName: liodata-scheduler-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi