image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/weatherupdate
  tag: 2.3.2

extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: CASSANDRA_IP
    value: ""
  - name: CASSANDRA_HOSTNAME
    value: "cassandra.ap-southeast-1.amazonaws.com"
  - name: CASSANDRA_PORT
    value: "9142"
  - name: CASSANDRA_DATACENTER
    value: "ap-southeast-1"
  - name: CASSANDRA_DB_TYPE
    value: "amazon_keyspace"
  - name: CASSANDRA_KEYSPACE
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: CASSANDRA_KEYSPACE
  - name: CASSANDRA_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: CASSANDRA_USERNAME
  - name: CASSANDRA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: CASSANDRA_PASSWORD
  - name: AWS_REGION
    value: "ap-southeast-1"
  - name: KAFKA_SERVER
    value: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_TOPIC_ACTUALDRIVINGDWELL
    value: "Driving_DwellTime"
  - name: KAFKA_TOPIC_REALTIMEMODEL
    value: "Real_Time_Model_Trained"
  - name: PREDICTIONAPI_NATS_URL
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: GRIDTYPE_ID
    value: "1000"
  - name: LATITUDE_MAX
    value: "1.470759"
  - name: LATITUDE_MIN
    value: "1.158702"
  - name: LONGITUDE_MAX
    value: "104.088481"
  - name: LONGITUDE_MIN
    value: "103.605545"
  - name: WEATHER_API_KEY
    value: "ac43a511d89f6109d335dc5a8c2ba438"
  - name: PS_WEATHERSERVICE_LOGFILE
    value: "/app/DrivingDwellTimePredictionLogs/BaseModels/WeatherService"
  - name: KAFKA_PRODUCER_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_USERNAME
  - name: KAFKA_PRODUCER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: REALTIME_MODEL_FOLDER_DRIVING
    value: "/san/new_py/StoppointLink_Models/RTModels/DrivingTime"
  - name: REALTIME_MODEL_FOLDER_DWELL
    value: "/san/new_py/StoppointLink_Models/RTModels/DwellTime"
  - name: NATS_SERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: NATS_ALERT_SUBJECT
    value: "NTA_PROD_CLOUD.AIML.Alerts.Alert"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace 
  - name: OTEL_SERVICE_NAME
    value: "weatherupdate"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: KAFKA_THRESHOLD_MINUTES
    value: "60"
  - name: MEMORY_THRESHOLD_MB
    value: "1800"
  - name: HEARTBEAT_THRESHOLD_MINS 
    value: "10"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: weatherupdate.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - weatherupdate.fms.itfs.lta.gov.sg
      secretName: weatherupdate-tls

serviceAccount:
  create: true
  name: weatherupdate-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-WEATHER

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: weatherupdate-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: weatherupdate-san-fsx-pv
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: weatherupdate
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: weatherupdate
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: weatherupdate-sa
        namespace: weatherupdate

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: weatherupdate-san-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "weatherupdate-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
