bases:
  - ../../global.yaml
  - ../app.yaml

releases:
  - name: lrd-busdispatchprocessing
    installed: true
    namespace: lrd-busdispatchprocessing
    chart: ecr-uat-helm-charts/python
    version: 0.2.1
    values:
      - default.values.yaml
      - "{{ .Environment.Name }}.values.yaml"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "{{ .Environment.Name }}.secretClass.yaml"
          - "--context"
          - "{{.Environment.KubeContext}}"

