apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: busdispatchservice-spc # keep -spc suffix
  namespace: busdispatchservice
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "UAT-APP-EKS-BUSDISPATCHSERVICE"
        objectType: "secretsmanager"
        jmesPath:
          - path: KEYCLOAK_CLIENT_SECRET
            objectAlias: KEYCLOAK_CLIENT_SECRET-alias
      - objectName: "UAT-DB-MONGODB"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_DB_PASS
            objectAlias: MONGO_DB_PASS-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: KEYCLOAK_CLIENT_SECRET # key whose corresponding value will have content of the secret
          objectName: KEYCLOAK_CLIENT_SECRET-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: MONGO_DB_PASS # key whose corresponding value will have content of the secret
          objectName: MONGO_DB_PASS-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque