image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-liodata

extraEnvs:
  - name: DB_SID
    value: "LRD"
  - name: DB_DATABASEMACHINEIP
    value: "prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: DB_BIDB_USER
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BIDB_USERNAME
  - name: DB_BIDB_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BIDB_PASSWORD
  - name: DB_BIDB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_USERNAME
  - name: DB_BIDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_PASSWORD
  - name: DB_DSDB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSDB_USERNAME
  - name: DB_DSDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSDB_PASSWORD
  - name: DB_DSLIODB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSLIODB_USERNAME
  - name: DB_DSLIODB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSLIODB_PASSWORD
  - name: DB_OPERATIONAL_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_OPERATIONALDB_USERNAME
  - name: DB_OPERATIONALDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_OPERATIONALDB_PASSWORD
  - name: DB_PORT
    value: "1581"
  - name: DB_CONNECTION_TIMEOUT
    value: "120"
  - name: DB_DRIVER_NAME
    value: "oracle.jdbc.driver.OracleDriver"
  - name: DB_MAX_ACTIVE_CONNECTIONS
    value: "40"
  - name: DB_MAX_IDLE_CONNECTIONS
    value: "0"
  - name: DB_MAX_WAIT_TIME
    value: "30000"
  - name: ME_NATSSERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: ME_LIOUPLOADPROCESSINGPATH
    value: "/san/MainETL/lioData"
  - name: ME_LOCALCACHERUNNINGURL
    value: "https://lrd-cache.fms.itfs.lta.gov.sg/v1/"
  - name: ME_LIODATASOURCELOCATION
    value: "/liodv/customer/LTA/exchange/BI_Statistic/VLD"
  - name: TZ
    value: "Asia/Singapore"
  - name: ME_BACKUPPATH
    value: "/LRD_Backup/"
  - name: ME_BACKUPENABLE
    value: "Y"
  - name: ME_DELETEFILESOFFSET
    value: "4"
  - name: ME_AIMLENABLE
    value: "true"
  - name: ME_AIMLLOC
    value: "/san/MainETL/Baseversion/Source"
  - name: ME_LIOCACHEUPDATESUBJECT
    value: "Update_cache"
  - name: ME_LIODELTAACTIVETIMESUBJECT
    value: "Delta_activation_time"
  - name: ME_LIOSTREAMNAME
    value: "LioData"
  - name: ME_NATSREPLICAS
    value: "3"
  - name: ME_NATS_RETENTION_MESSAGE_DAYS
    value: "7"
  - name: ME_FILESTOPROCESSFOLDER
    value: "FilesToProcess"
  - name: ME_FILESPROCESSEDFOLDER
    value: "FilesProcessed"
  - name: ME_FILESNOTPROCESSEDFOLDER
    value: "FilesNotProcessed"
  - name: ME_FILESLOADEDFOLDER
    value: "FilesLoaded"
  - name: ME_FILESTOLOADFOLDER
    value: "FilesToLoad"
  - name: ME_LIODB_TO_DSDB_TRANSFER
    value: "Single"
  - name: ME_DAILYVERSIONMATCHTIME
    value: "00:05"
  - name: ME_TIMEGAPINVERSIONMATCH
    value: "24"
  - name: ME_SP_BASEVERSION_1
    value: "DSLIODB.ProcessDataSupply.P_Load_Dimension_Data,BASEVERSION , INCREMENTAL_VERSION"
  - name: ME_SP_DAILY_1
    value: "DSLIODB.P_POPULATE_SCHEDULEDTABLES,BASEVERSION, INCREMENTAL_VERSION, SERVICEDAY"
  - name: ME_CTL_FILE_GENERATION
    value: "MAINETL"
  - name: ME_LIODATABASEVERSIONFILENAME
    value: "VLD_BASEVERSION.csv"
  - name: ME_SP_BASEVERSION_2
    value: "DSLIODB.ProcessDataSupply.P_Update_Baseversion,BASEVERSION, INCREMENTAL_VERSION"
  - name: ME_SP_BASEVERSION_3
    value: "DSLIODB.ProcessDataSupply.P_Update_History_Data,BASEVERSION,PREVIOUS_BASEVERSION, INCREMENTAL_VERSION, PREV_INCREMENTAL_VERSION"
  - name: ME_SP_BASEVERSION_4
    value: "DSLIODB.P_Attach_Package,BASEVERSION, INCREMENTAL_VERSION"
  - name: ME_SP_DAILY_2
    value: "DSLIODB.ProcessDataSupply.P_Update_Calendar,BASEVERSION, INCREMENTAL_VERSION, SERVICEDAY"
  - name: ME_SP_DAILY_3
    value: "DSLIODB.ProcessDataSupply.P_ValidateAITPData,BASEVERSION, SERVICEDAY"
  - name: "THREAD_STALL_THRESHOLD_SECS"
    value: "86500"
  - name: NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: MEMORY_THRESHOLD_MB
    value: "700"
  - name: ISLEASEENABLE
    value: "true"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: lrd-liodata
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: lrd-liodata
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: lrd-liodata-sa
        namespace: lrd-liodata

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-liodata-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-liodata-san-fsx-pv
  
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-liodata-liodv-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-liodata-liodv-fsx-pv

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-liodata-san-s3-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-liodata-san-s3-pv

serviceAccount:
  create: true
  name: lrd-liodata-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-LRD

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-liodata-san-fsx-pvc

  - name: fsx-liodata
    persistentVolumeClaim:
      claimName: lrd-liodata-liodv-fsx-pvc

  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-liodata-spc"

  - name: s3-data
    persistentVolumeClaim:
      claimName: lrd-liodata-san-s3-pvc

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"
  - name: fsx-liodata
    mountPath: "/liodv"
  - name: s3-data
    mountPath: "/LRD_Backup"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-liodata.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-liodata.fms.itfs.lta.gov.sg
      secretName: lrd-liodata-tls

