apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-liodata-spc # keep -spc suffix
  namespace: lrd-liodata
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "UAT-APP-EKS-LRD-DB"
        objectType: "secretsmanager"
        jmesPath:
          - path: LRD_PASSWORD
            objectAlias: LRD_PASSWORD-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: LRD_PASSWORD # key whose corresponding value will have content of the secret
          objectName: LRD_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque