apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-ccrealtimepassage-spc # keep -spc suffix
  namespace: lrd-ccrealtimepassage
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "UAT-APP-EKS-LRD-DB"
        objectType: "secretsmanager"
        jmesPath:
          - path: LRD_PASSWORD
            objectAlias: LRD_PASSWORD-alias
      - objectName: "AmazonMSK_UAT-SECRET-KAFKA-LRD-CCREALTIMEUPLOAD"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: KAFKA_PASSWORD-alias
          - path: username
            objectAlias: KAFKA_USERNAME-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: LRD_PASSWORD # key whose corresponding value will have content of the secret
          objectName: LRD_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: KAFKA_PASSWORD
          objectName: KAFKA_PASSWORD-alias
        - key: KAFKA_USERNAME
          objectName: KAFKA_USERNAME-alias
      secretName: aws-secrets-manager-secret
      type: Opaque