apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: can-conditionalmonitoring-spc # keep -spc suffix
  namespace: can-conditionalmonitoring
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-OPERATIONALDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: OPERATIONALDB_USERNAME-alias        
          - path: password
            objectAlias: OPERATIONALDB_PASSWORD-alias
      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-CAN"
        objectType: "secretsmanager"
        jmesPath:
              - path: username
                objectAlias: username-alias
              - path: password
                objectAlias: password-alias
  secretObjects:
    - data:
        - key: OPERATIONALDB_USERNAME
          objectName: OPERATIONALDB_USERNAME-alias
        - key: OPERATIONALDB_PASSWORD
          objectName: OPERATIONALDB_PASSWORD-alias
        - key: username # key whose corresponding value will have content of the secret
          objectName: username-alias 
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque