extraEnvs:
  - name: DB_URL
    value: "jdbc:oracle:thin:@//uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com:1521/LRD"
  - name: DB_USERNAME
    value: "OPERATIONALDB"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DRIVER_CLASS
    value: "oracle.jdbc.OracleDriver"
  - name: DB_PLATFORM
    value: "org.hibernate.dialect.OracleDialect"
  - name: BATCH_DEVICE_ENABLED
    value: "false"
  - name: BATCH_DEVICE_STATUS_SIZE
    value: "1000"
  - name: BATCH_DEVICE_INFO_SIZE
    value: "1000"
  - name: BATCH_FLUSH_INTERVAL_MS
    value: "300000"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS 
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_CONSUMER_DCM_TOPIC 
    value: "dcm.device.kafka.topic"
  - name: KAFKA_USERNAME 
    value: "can-conditionalmonitoring"
  - name: KAFKA_PASSWORD 
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: NATS_BROKER_URL 
    value: "nats.fms-uat.itfs.lta.gov.sg"
  - name: NATS_ALERT_TOPIC 
    value: "CAN.Alerts.Alert"
  - name: APPLICATION_ENV 
    value: "uat"
  - name: TZ
    value: "Asia/Singapore"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/success-codes: "200,302"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: can-conditionalmonitoring.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - can-conditionalmonitoring.fms-uat.itfs.lta.gov.sg
      secretName: can-conditionalmonitoring-tls

serviceAccount:
  create: true
  name: can-conditionalmonitoring-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-CAN-CONDITIONALMONITORING
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "can-conditionalmonitoring-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

keda:
  enabled: true
  secret:
    existingSecret: "aws-secrets-manager-secret"
    usernameKey: "username"
    passwordKey: "password"
    sasl: "scram_sha512"
    tls: "enable"
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
          consumerGroup: "shared-consumer-group"
          topic: "dcm.device.kafka.topic"
          lagThreshold: "5000"