apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: data-ingester-spc # keep -spc suffix
  namespace: data-ingester
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-CAN"
        objectType: "secretsmanager"
        jmesPath:
              - path: username
                objectAlias: username-alias
              - path: password
                objectAlias: password-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: username # key whose corresponding value will have content of the secret
          objectName: username-alias 
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque