extraEnvs:
  - name: SERVER_PORT
    value: "8181"
  - name: SPRING_APPLICATION_NAME 
    value: "can-data-ingester"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS 
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_PRODUCER_TOPIC  
    value: "liovolta-ch.liovolta.tst.app.ingest-fusionapi.1"
  - name: KAFKA_USERNAME 
    value: "data-ingester"
  - name: KAFKA_PASSWORD 
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: MQTT_BROKER_URL  
    value: "tcp://emqx.fms-uat.itfs.lta.gov.sg:8883"
  - name: MQTT_SUBSCRIBE_TOPIC 
    value: "lio/env0/can/Uplink/Vehicle/#"
  - name: HOMEDIR  
    value: "/app"
  - name: KAFKA_PRODUCER_TELLTALE_TOPIC  
    value: "telltale.nta.app.ingest-telltale.1"
  - name: TZ
    value: "Asia/Singapore"
  - name: KAFKA_DCM_PRODUCER_TOPIC
    value: dcm.device.kafka.topic 
  - name: MQTT_DCM_SUBSCRIBE_TOPIC
    value: "lio/env0/dcm/#"
  - name: TOPIC_VEHICLEID_INDEX
    value: "3"
  - name: TOPIC_DEVICEID_INDEX
    value: "5"
  - name: HOMEDIR  
    value: "/app" 
  - name: MQTT_SHARED_GROUP
    value: "dataingester-group"
  - name: NATS_BROKER_URL
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: NATS_ALERT_TOPIC  
    value: "NTA_PROD_CLOUD.CAN.Alerts.Alert"
  - name: APPLICATION_ENV  
    value: "dev"
  - name: MEMORY_THRESHOLD_MB
    value: "600"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/success-codes: "200,404" # temporary workaround for 404 from health check
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: data-ingester.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - data-ingester.fms-uat.itfs.lta.gov.sg
      secretName: data-ingester-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

serviceAccount:
  create: true
  name: data-ingester-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-DATA-INGESTER
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "data-ingester-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true