apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kps-kube-controller-manager
  namespace: observability
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  namespaceSelector:
    matchNames:
      - "default"
  endpoints:
  - port: https
    scheme: https
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    path: "/apis/metrics.eks.amazonaws.com/v1/kcm/container/metrics"
    relabelings:
    - targetLabel: monitoringJob
      replacement: kubecontrollerManager_metrics_via_api_server