image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws
  tag: 2.1.0

useFipsEndpoint: false

driverWritesSecrets: true

rbac:
  install: true

secrets-store-csi-driver:
  install: false

  rbac:
    install: true
    pspEnabled: false

  syncSecret:
    enabled: true

  linux:
    enabled: true

  image:
    repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/registry.k8s.io/csi-secrets-store/driver
    tag: v1.5.6

  crds:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/registry.k8s.io/csi-secrets-store/driver-crds
    tag: v1.5.6

  registrarImage:
    repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/bakery-central/registry-k8s-io/sig-storage/csi-node-driver-registrar
    tag: v2.13.0

  livenessProbeImage:
    repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/registry.k8s.io/sig-storage/livenessprobe
    tag: v2.17.0