environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../../global.yaml
  - ../../app.yaml

releases:
  # https://aws.github.io/secrets-store-csi-driver-provider-aws
  - name: secrets-store-csi-provider
    namespace: kube-system
    installed: true
    chart: secrets-store-csi-driver-provider-aws/secrets-store-csi-driver-provider-aws
    version: 2.2.2
    values:
      - default.values.yaml
      - {{ .Environment.Name }}.values.yaml