image:
  repository: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/obelisk

extraEnvs:
  - name: AMISERVER__HOST
    value: "asterisk1.fms.itfs.lta.gov.sg"
  - name: AMISERVER__PORT 
    value: "5038"
  - name: AMISERVER__USER
    value: "obelisk" 
  - name: AMISERVER__PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: AMISERVER_PASSWORD
  - name: MESSAGING__KAFKA__BOOTSTRAPSERVERS
    value: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: MESSAGING__KAFKA__USEMSKAUTHENTICATION
    value: "true"
  - name: KAFKA_USERNAME
    value: "obelisk"   
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: VOICE_BI_REPORTING_TOPIC
    value: "cc_lrd_voice"   
  - name: ZMQ__REMOTEHOST
    value: "lio.fms.itfs.lta.gov.sg"   
  - name: ZMQ__REMOTEPORT
    value: "9002"
  - name: ZMQ__LOCALPORT
    value: "9003"
  - name: FSX__ANNOUNCEMENTSCC
    value: P:\
  - name: FSX__ANNOUNCEMENTSASTERISK
    value: "/mnt/fsx/"
  - name: AMISERVER__HANGUPDELAYMSANNOUNCEMENT
    value: "7000"
  - name: AMISERVER__HANGUPDELAYMSCALL 
    value: "1000"
  - name: TZ
    value: "Asia/Singapore"

service:
  type: LoadBalancer
  label: obelisk
  port: 9003
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-name: prd-app-intra-eks-app-nlb-oblsk
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0d0b84f3370f54b4b #PRD-APP-INTRA-EKS-APP-SG-NLB-OBLSK
      # service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
      external-dns.alpha.kubernetes.io/hostname: obelisk.fms.itfs.lta.gov.sg
      alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
      service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=prd-bk-logs,access_logs.s3.prefix=obelix,deletion_protection.enabled=true
  selector:
    app.kubernetes.io/instance: obelisk

serviceAccount:
  create: true
  name: obelisk-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-OBELISK
