apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb-internal-app

spec:
  scheme: internal
  group:
    name: internal-group-app
  sslPolicy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
  loadBalancerAttributes:
    - key: access_logs.s3.enabled
      value: "true"
    - key: access_logs.s3.bucket
      value: "prd-bk-logs"
    - key: access_logs.s3.prefix
      value: "alb-app-logs"
    - key: routing.http.drop_invalid_header_fields.enabled
      value: "true"
    - key: deletion_protection.enabled
      value: "true"
    - key: idle_timeout.timeout_seconds
      value: "300"