apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: liodata-webapi-spc # keep -spc suffix
  namespace: liodata-webapi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-PPADMIN"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: password-alias
      - objectName: "PRD-KEYCLOAK-CLIENT-LIODATAWEBAPI"
        objectType: "secretsmanager"
        jmesPath:
          - path: client_secret
            objectAlias: client_secret-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: client_secret # key whose corresponding value will have content of the secret
          objectName: client_secret-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: password
          objectName: password-alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque