extraEnvs:
  - name: SERVER_PORT
    value: "8003"
  - name: SPRING_APPLICATION_NAME 
    value: "can-dataprocessor"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS 
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_CONSUMER_LIOVOLTA_TOPIC  
    value: "liovolta-ch.liovolta.tst.app.ingest-fusionapi.1"
  - name: KAFKA_CONSUMER_TELLTALE_TOPIC  
    value: "telltale.lta.app.ingest-telltale.1"
  - name: KAFKA_USERNAME 
    value: "can-dataprocessor"
  - name: KAFKA_PASSWORD 
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: NATS_BROKER_URL 
    value: "nats.fms-uat.itfs.lta.gov.sg"
  - name: TZ
    value: "Asia/Singapore" 

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/success-codes: "200,302"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: can-dataprocessor.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - can-dataprocessor.fms-uat.itfs.lta.gov.sg
      secretName: can-dataprocessor-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

serviceAccount:
  create: true
  name: can-dataprocessor-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-CAN-DATAPROCESSOR
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "can-dataprocessor-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true