replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/softphonebackend
  tag: 1.5.0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 6014

podDisruptionBudget:
  enabled: true
  maxUnavailable: 0 

resources:
  limits:
    cpu: 512m
    memory: 1Gi
  requests:
    cpu: 128m
    memory: 1Gi

livenessProbe: 
  httpGet:
    path: "/health/live"
    port: 6014
    scheme: HTTP
  initialDelaySeconds: 40
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3

readinessProbe: 
  httpGet:
    path: "/health/ready"
    port: 6014
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 60
  successThreshold: 1
  failureThreshold: 3

nodeSelector:
  karpenter.sh/nodepool: application-node-pool