extraEnvs:
  - name: ENVIRONMENT_PREFIX
    value: "env0"
  - name: AMISERVER__HOST
    value: "asterisk1.fms-uat.itfs.lta.gov.sg"
  - name: AMISERVER__PORT
    value: "5038"
  - name: AMISERVER__USER
    value: "softphone"
  - name: AMISERVER__PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: AMISERVER_PASSWORD
  - name: MESSAGING__NATS__URL
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: MESSAGING__KAFKA__BOOTSTRAPSERVERS
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: MESSAGING__KAFKA__USEMSKAUTHENTICATION
    value: "true"
  - name: KAFKA_USERNAME
    value: "softphonebackend"
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: VOICE_BI_REPORTING_TOPIC
    value: "voice_bi_topic"
  - name: DATABASE__MONGO__HOST
    value: "uat-app-mongo-mongo1.fms-uat.itfs.lta.gov.sg:27817,uat-app-mongo-mongo2.fms-uat.itfs.lta.gov.sg:27817,uat-app-mongo-mongo3.fms-uat.itfs.lta.gov.sg:27817"
  - name: DATABASE__MONGO__USER
    value: "lio"
  - name: DATABASE__MONGO__PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: MONGO_DB_PASS
  - name: DATABASE__MONGO__PARAMETERS
    value: "authSource=admin&authMechanism=SCRAM-SHA-256"
  - name: KEYCLOAK__AUTHORITYURL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg"
  - name: KEYCLOAK__REALM
    value: "LIO"
  - name: KEYCLOAK__SOFTPHONEBACKEND
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KEYCLOAK_CLIENT_SECRET
  - name: IDENTITYPROVIDER
    value: "Keycloak"
  - name: TZ
    value: "Asia/Singapore"
     
ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/health/ready"
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: softphonebackend.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - softphonebackend.fms-uat.itfs.lta.gov.sg
      secretName: softphonebackend-tls

serviceAccount:
  create: true
  name: softphonebackend-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-SOFTPHONEBACKEND
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "softphonebackend-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true