apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rtprediction-spc # keep -spc suffix
  namespace: rtprediction
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-AIML"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: KAFKA_USERNAME-alias        
          - path: password
            objectAlias: KAFKA_PASSWORD-alias
      - objectName: "PRD-APP-KEYSPACE"
        objectType: "secretsmanager"
        jmesPath:
          - path: CASSANDRA_KEYSPACE
            objectAlias: CASSANDRA_KEYSPACE-alias
          - path: CASSANDRA_USERNAME
            objectAlias: CASSANDRA_USERNAME-alias
          - path: CASSANDRA_PASSWORD
            objectAlias: CASSANDRA_PASSWORD-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: KAFKA_PASSWORD # key whose corresponding value will have content of the secret
          objectName: KAFKA_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: KAFKA_USERNAME # key whose corresponding value will have content of the secret
          objectName: KAFKA_USERNAME-alias # name of the mounted content to sync.
        - key: CASSANDRA_KEYSPACE # key whose corresponding value will have content of the secret
          objectName: CASSANDRA_KEYSPACE-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: CASSANDRA_USERNAME # key whose corresponding value will have content of the secret
          objectName: CASSANDRA_USERNAME-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: CASSANDRA_PASSWORD # key whose corresponding value will have content of the secret
          objectName: CASSANDRA_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque
