extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: KEYCLOAK_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg"
  - name: KEYCLOAK_REALM
    value: "LIO"
  - name: KEYCLOAK_CLIENT_ID
    value: "admin-cli"
  - name: CLIENT_ID
    value: "monitoring-keycloak"
  - name: CLIENT_SECRET
    value: "ztJ79fQPuRbbEI2Pz66cTxvI5Rh6PlOb"
  - name: POLL_INTERVAL
    value: "30"
  - name: MONITORED_CLIENTS
    value: "DDM,liodata-webapi,MTV,client-dcvl"
  - name: VERIFY_SSL
    value: "false"

ingress:
  enabled: true
  className: alb-internal-app
  hosts:
    - host: monitoring-keycloak-metrics.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - monitoring-keycloak-metrics.fms.itfs.lta.gov.sg
      secretName: monitoring-keycloak-metrics-tls
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-08b5165e42765ab7d
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/healthcheck-path: "/metrics"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
