image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/ddm-webapi

extraEnvs:
  - name: PROPERTY_JDBC_HOST
    value: "prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: PROPERTY_JDBC_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: username
  - name: PROPERTY_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: LICENSE_KEY
    value: "YNBs+OUmTKtwglsQujhVsc8kglxByhqTzaM6rTvoDE4nCsijA1+EqWYGWITDLOGZV1/xX5S5DU5lAQimkqWNOA1Nj7P9mPTDko6xNYPxh6ReiaquL7F5kerBJAxxPkcImoF55+jLg5njVXgVtAdFbD/A3la1snbq8zz73RBAwAROd798o275UtXLU/IE4kBWD8zIaZkwBqhLrmQ84tWw8xMGS3fMfCkvAKfXfpvUskyxwd+a2Br6YeyPV8mx2QCO45dDjh5XJs3gqYbFcIzVH3kqZEfmJZAPrKWW7RJ+QeF0o44w2F/rj/SjzomNRi1L"
  - name: CONNECTION_STRINGS_DATA_MODEL_CONNECTION_STRING
    value: metadata=/app/DDM.EntityFramework/bin/Models.DataModel.csdl|/app/DDM.EntityFramework/bin/Models.DataModel.ssdl|/app/DDM.EntityFramework/bin/Models.DataModel.msl;provider=Devart.Data.Oracle;provider connection string="Server=(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = $(PROPERTY_JDBC_HOST))(PORT = 1581))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = DDM)));direct=true;uid=ddmprd;pwd=$(PROPERTY_JDBC_PASSWORD);License Key=$(LICENSE_KEY);"
  - name: LOGGING_LOGLEVEL_DEFAULT
    value: "Information"
  - name: LOGGING_CONSOLE_LOGLEVEL_DEFAULT
    value: "Information"
  - name: LOGGING_FILELOGGER_OPTIONS_FOLDERPATH
    value: "/ddm/logs/"
  - name: LOGGING_FILELOGGER_OPTIONS_FILENAME
    value: "DDMWebApiCore.log_{date}"
  - name: LOGGING_FILELOGGER_LOGLEVEL_DDM
    value: "Information"
  - name: FILE_SERVER_STORAGE_PATH
    value: "/ddm/storage/downloaddata/"
  - name: STAGING_STORAGE_PATH
    value: "/ddm/storage/staging/"
  - name: ALLOWED_HOST
    value: "https://ddm-webclient.fms.itfs.lta.gov.sg"
  - name: KEYCLOAK_SERVER_REALM_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO"
  - name: KEYCLOAK_CLIENT_ID
    value: "DDM"
  - name: KEYCLOAK_AUTHENTICATION
    value: "true"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: client_secret
  - name: KEYCLOAK_TOKEN_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/token"
  - name: KEYCLOAK_LOGOUT_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/logout"
  - name: KEYCLOAK_USER_INFO_URL
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/userinfo"
  - name: TZ
    value: "Asia/Singapore"
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: OPENTELEMETRY_COLLECTOR_URL
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: NATS_SERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: SAF_FILE_UPLOAD_DURATION_IN_HOURS
    value: "24"
  - name: VEHICLE_DOWNLOAD_FAILURE_STATS_DURATION_IN_HOURS
    value: "24"
  - name: NATS_SUBJECT_ALERTS
    value: "DDM.Alerts.Alert"
  - name: ENVIRONMENT
    value: "prod"
  - name: DDM_MEMORY_THRESHOLD_MB
    value: "4000"

serviceAccount:
  create: true
  name: ddm-webapi-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-DDM

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ddm-webapi-ddm-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: ddm-webapi-ddm-fsx-pv

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: ddm-webapi-ddm-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "ddm-webapi-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/ddm"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-08b5165e42765ab7d # PRD-APP-INTRA-EKS-APP-SG-ALB-EKS
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
  hosts:
    - host: ddm-webapi.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - ddm-webapi.fms.itfs.lta.gov.sg
      secretName: ddm-webapi-tls

resources:
  limits:
    cpu: 512m
    memory: 4Gi
  requests:
    cpu: 128m
    memory: 2Gi
