apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ddm-webapi-spc # keep -spc suffix
  namespace: ddm-webapi
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "PRD-KEYCLOAK-CLIENT-DDM"
        objectType: "secretsmanager"
        jmesPath:
          - path: client_secret
            objectAlias: client_secret-alias
      - objectName: "PRD-APP-RDS-ORACLE-DDMPRD"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: password-alias
          - path: username
            objectAlias: username-alias            
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: client_secret # key whose corresponding value will have content of the secret
          objectName: client_secret-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: username
          objectName: username-alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque