apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ddm-webapi-spc # keep -spc suffix
  namespace: ddm-webapi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "UAT-APP-EKS-DDM"
        objectType: "secretsmanager"
        jmesPath:
          - path: KEYCLOAK_CLIENT_SECRET
            objectAlias: KEYCLOAK_CLIENT_SECRET-alias
      - objectName: "UAT-EKS-APP-ORACLE-DDM"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: password-alias
          - path: LICENSE_KEY
            objectAlias: LICENSE_KEY-alias
          - path: host
            objectAlias: host-alias            
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: KEYCLOAK_CLIENT_SECRET # key whose corresponding value will have content of the secret
          objectName: KEYCLOAK_CLIENT_SECRET-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: LICENSE_KEY # key whose corresponding value will have content of the secret
          objectName: LICENSE_KEY-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: host
          objectName: host-alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque