extraEnvs:
  - name: PROPERTY_JDBC_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: host
  - name: PROPERTY_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: LICENSE_KEY
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LICENSE_KEY
  - name: CONNECTION_STRINGS_DATA_MODEL_CONNECTION_STRING
    value: metadata=/app/DDM.EntityFramework/bin/Models.DataModel.csdl|/app/DDM.EntityFramework/bin/Models.DataModel.ssdl|/app/DDM.EntityFramework/bin/Models.DataModel.msl;provider=Devart.Data.Oracle;provider connection string="Server=(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = $(PROPERTY_JDBC_HOST))(PORT = 1581))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = DDM)));direct=true;uid=ddmprd;pwd=$(PROPERTY_JDBC_PASSWORD);License Key=$(LICENSE_KEY);"
  - name: LOGGING_LOGLEVEL_DEFAULT
    value: "Information"
  - name: LOGGING_CONSOLE_LOGLEVEL_DEFAULT
    value: "Information"
  - name: LOGGING_FILELOGGER_OPTIONS_FOLDERPATH
    value: "/ddm/logs/"
  - name: LOGGING_FILELOGGER_OPTIONS_FILENAME
    value: "DDMWebApiCore.log_{date}"
  - name: LOGGING_FILELOGGER_LOGLEVEL_DDM
    value: "Information"
  - name: FILE_SERVER_STORAGE_PATH
    value: "/ddm/storage/downloaddata/"
  - name: STAGING_STORAGE_PATH
    value: "/ddm/storage/staging/"
  - name: ALLOWED_HOST
    value: "https://ddm-webclient.fms-uat.itfs.lta.gov.sg/"
  - name: KEYCLOAK_SERVER_REALM_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg/realms/LIO"
  - name: KEYCLOAK_CLIENT_ID
    value: "DDM"
  - name: KEYCLOAK_AUTHENTICATION
    value: "true"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KEYCLOAK_CLIENT_SECRET
  - name: KEYCLOAK_TOKEN_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/token"
  - name: KEYCLOAK_LOGOUT_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/logout"
  - name: KEYCLOAK_USER_INFO_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg/realms/LIO/protocol/openid-connect/userinfo"
  - name: TZ
    value: "Asia/Singapore"
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: OPENTELEMETRY_COLLECTOR_URL
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: SAF_FILE_UPLOAD_DURATION_IN_HOURS
    value: "24"
  - name: VEHICLE_DOWNLOAD_FAILURE_STATS_DURATION_IN_HOURS
    value: "24"
  - name: NATS_SUBJECT_ALERTS
    value: "DDM.Alerts.Alert"
  - name: ENVIRONMENT
    value: "test2"
  - name: DDM_MEMORY_THRESHOLD_MB
    value: "500"

serviceAccount:
  create: true
  name: ddm-webapi-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-DDM

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ddm-webapi-ddm-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: ddm-webapi-ddm-fsx-pv

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: ddm-webapi-ddm-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "ddm-webapi-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/ddm"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9 # UAT-APP-INTRA-EKS-APP-SG-ALB-EKS
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: ddm-webapi.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - ddm-webapi.fms-uat.itfs.lta.gov.sg
      secretName: ddm-webapi-tls

resources:
  limits:
    cpu: 512m
    memory: 4Gi
  requests:
    cpu: 128m
    memory: 2Gi
