image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/fsx-csi-driver/aws-fsx-openzfs-csi-driver
  tag: v1.2.0

sidecars:
  livenessProbe:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
      tag: v2.15.0-eks-1-33-9
  nodeDriverRegistrar:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
      tag: v2.13.0-eks-1-33-9
      # this above mistype should be changed to this below
      # repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar 
  provisioner:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
      tag: v5.2.0-eks-1-33-9
  resizer:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/external-resizer
      tag: v1.13.2-eks-1-33-9
  snapshotter:
    image:
      repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter
      tag: v8.2.1-eks-1-33-9