kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.openzfs.csi.aws.com
parameters:
  ResourceType: "volume" #REQUIRED
  ParentVolumeId: '"fsvol-00650ba64f735419b"' #REQUIRED - fsx - > PRD-APP-INTRA-EKS-APP-APP-FSX-EKS-APP
  CopyTagsToSnapshots: "false"
  DataCompressionType: '"NONE"'
  NfsExports: '[{"ClientConfigurations": [{"Clients": "*", "Options": ["rw","crossmnt"]}]}]'
  ReadOnly: "false"
  RecordSizeKiB: "128"
  StorageCapacityReservationGiB: "-1"
  StorageCapacityQuotaGiB: "-1"
  UserAndGroupQuotas: '[{"Type": "USER", "Id": 1, "StorageCapacityQuotaGiB": 10}]'
  Tags: '[{"Key": "OPENZFS", "Value": "OPENZFS"}]'
  OptionsOnDeletion: '["DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"]' #SET ON DELETION
reclaimPolicy: Retain
allowVolumeExpansion: false #Not supported for OpenZFS volumes
mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - timeo=600