image:
  pullPolicy: IfNotPresent
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/ghcr.io/stakater/reloader
  tag: v1.4.14-patched-1

reloader:
  watchGlobally: true
  ignoreSecrets: false
  ignoreConfigMaps: false
  logFormat: json
  logLevel: info

  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
