extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: CASSANDRA_IP
    value: ""
  - name: CASSANDRA_HOSTNAME
    value: "cassandra.ap-southeast-1.amazonaws.com"
  - name: CASSANDRA_PORT
    value: "9142"
  - name: CASSANDRA_DATACENTER
    value: "ap-southeast-1"
  - name: CASSANDRA_DB_TYPE
    value: "amazon_keyspace"
  - name: CASSANDRA_KEYSPACE
    value: "UAT_APP_KEYSPACE"
  - name: CASSANDRA_USERNAME
    value: "UAT-IAMU-KEYSPACE-at-381491900351"
  - name: CASSANDRA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: CASSANDRA_PASSWORD
  - name: PROPERTY_PREDICTION_API_LOG_CONFIG
    value: "/app/PredictionAPIService/prediction-config/prediction-api-log4j2.xml"
  - name: PREDICTIONAPI_NATS_URL
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: NATS_DRIVING_SUBJECT
    value: "currentDrivingPredictions"
  - name: NATS_DWELL_SUBJECT
    value: "currentDwellPredictions"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: predictionapi.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - predictionapi.fms-uat.itfs.lta.gov.sg
      secretName: predictionapi-tls

serviceAccount:
  create: true
  name: predictionapi-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-PREDICTIONAPI

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

# Add volumes for secrets store
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "predictionapi-spc"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
