environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../global.yaml
  - ../app.yaml

releases:
  - name: kps-crds
    installed: true
    namespace: observability
    chart: ecr-uat-helm-charts/helm/prometheus-operator-crds
    version: 22.0.1

  - name: kps
    installed: true
    namespace: observability
    chart: ecr-uat-helm-charts/helm/kube-prometheus-stack
    version: 72.5.2
    needs:
      - kps-crds
    values:
      - default.values.yaml
      - "{{ .Environment.Name }}.values.yaml"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
          - "--context"
          - "{{ .Environment.KubeContext }}"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "{{ .Environment.Name }}.prometheus.ingress.yaml"
          - "--context"
          - "{{ .Environment.KubeContext }}"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "alb-controller-monitoring/"
          - "-f"
          - "cert-manager-monitoring/"
          - "-f"
          - "control-plane-monitoring/"
          - "-f"
          - "ingress-nginx-monitoring/"
          - "--context"
          - "{{ .Environment.KubeContext }}"

  - name: nats-exporter
    installed: true
    namespace: observability
    chart: ecr-uat-helm-charts/prometheus-nats-exporter
    version: 2.18.0
    needs:
      - kps-crds
    values:
      - nats-monitoring/default.values.yaml
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "nats-monitoring/nats-exporter-service"
          - "--context"
          - "{{ .Environment.KubeContext }}"
