prometheus:
  prometheusSpec:
    scrapeClasses:
      - name: default-class-to-add-cluster-identifying-labels
        default: true
        relabelings:
          - targetLabel: cluster
            replacement: uat-app-intra-eks-app-eks-cluster
          - targetLabel: scope
            replacement: infrastructure
    additionalScrapeConfigs:
      - job_name: 'nats-engine'
        static_configs:
          - targets: ['nats-engine.fms-uat.itfs.lta.gov.sg']
        scrape_interval: 10s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
        metric_relabel_configs:
          - target_label: scope
            replacement: application
      - job_name: keycloak-users
        static_configs:
          - targets: ['monitoring-keycloak-metrics.fms-uat.itfs.lta.gov.sg']
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
        metric_relabel_configs:
          - target_label: scope
            replacement: application
      - job_name: lio-data
        static_configs:
          - targets: ['liodata-webapi.fms-uat.itfs.lta.gov.sg']
        scrape_interval: 1m
        scrape_timeout: 15s
        metrics_path: /metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
        metric_relabel_configs:
          - target_label: scope
            replacement: application
    remoteWrite:
      - url: "https://prometheus-man.fms-uat.itfs.lta.gov.sg/api/v1/write"
        name: app-to-man-remoteWrite
        messageVersion: V2.0
        sendExemplars: true
        sendNativeHistograms: true
        tlsConfig:
          insecureSkipVerify: true
        remoteTimeout: 60s
        queueConfig:
          capacity: 10000
          maxShards: 50
          minShards: 1
          maxSamplesPerSend: 5000
          batchSendDeadline: 10s
          minBackoff: 30ms
          maxBackoff: 5s