environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../../global.yaml
  - ../../app.yaml

releases:
# https://artifacthub.io/packages/helm/nats/nats
  - name: nats
    namespace: nats
    chart: nats/nats
    version: 2.12.6
    values:
      - default.values.yaml
      - {{ .Environment.Name }}.values.yaml
      - {{toYaml .Values | nindent 8}}