global:
  labels:
    app: "nats"
  image:
    registry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/registry-1.docker.io

container:
  image:
    fullImageName: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/registry-1.docker.io/library/nats:2.12.6-alpine

reloader:
  image:
    fullImageName: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/registry-1.docker.io/natsio/nats-server-config-reloader:0.21.1

natsBox:
  container:
    image:
      fullImageName: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/registry-1.docker.io/natsio/nats-box:0.19.3
 
service:
  enabled: true
  merge:
    spec:
      type: LoadBalancer
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-name: prd-app-intra-eks-app-nlb-nats
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0b378d8d801e81920 # PRD-APP-INTRA-EKS-APP-SG-NLB-NATS
        external-dns.alpha.kubernetes.io/hostname: nats.fms.itfs.lta.gov.sg
        alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
        service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=prd-bk-logs,access_logs.s3.prefix=nats,deletion_protection.enabled=true
  ports:
    nats:
      enabled: true
    websockets:
      enabled: false
    monitor:
      enabled: false

config:
  merge:
    max_payload: 33554432   # 32MB 
    max_pending: 268435456  # 256MB per client
  mqtt:
    enabled: false
  jetstream:
    enabled: true
    memoryStore:
      enabled: true
      maxSize: 1Gi
    fileStore:
      enabled: false
      dir: /data/jetstream
      pvc:
        enabled: false
        size: 5Gi
        storageClassName: ""
  cluster:
    enabled: true
    replicas: 3
  service:
    enabled: false
  websocket:
    enabled: false
    ingress:
      enabled: false

podTemplate:
  topologySpreadConstraints:
    - labelSelector:
      matchLabels:
        app: "nats"
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone # <---spread those pods evenly over all availability zones
      whenUnsatisfiable: ScheduleAnyway