global:
  labels:
    app: "nats"
 
service:
  enabled: true
  merge:
    spec:
      type: LoadBalancer
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-name: uat-app-intra-eks-app-nlb-nats
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-079140133838bd443 #temp
        external-dns.alpha.kubernetes.io/hostname: nats.fms-uat.itfs.lta.gov.sg
        alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
        service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=uat-bk-logs,access_logs.s3.prefix=nats,deletion_protection.enabled=true
  ports:
    nats:
      enabled: true
    websockets:
      enabled: false
    monitor:
      enabled: false
 
config:
  merge:
    max_payload: 33554432   # 32MB 
    max_pending: 268435456  # 256MB per client
  mqtt:
    enabled: false
  jetstream:
    enabled: true
    memoryStore:
      enabled: true
      maxSize: 1Gi
    fileStore:
      enabled: false
      dir: /data/jetstream
      pvc:
        enabled: false
        size: 5Gi
        storageClassName: ""
  cluster:
    enabled: true
    replicas: 3
  service:
    enabled: false
  websocket:
    enabled: false
    ingress:
      enabled: false
 
podTemplate:
  topologySpreadConstraints:
    - labelSelector:
      matchLabels:
        app: "nats"
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone # <---spread those pods evenly over all availability zones
      whenUnsatisfiable: ScheduleAnyway