image:
  repository:  381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-fsxtos3

extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: AWS_S3_BUCKET
    value: "uat-app-bk-gut-bisaf"
  - name: AWS_REGION
    value: "ap-southeast-1"
  - name: AWS_S3_FOLDER_PREFIX
    value: "cc_voice_recordings_"
  - name: VOICE_FILES_DEFAULT_RETENTION_DAYS
    value: "60"
  - name: VOICE_FILES_OVERRIDE_RETENTION_DAYS
    value: "1075"
  - name: VOICE_FILE_DIRECTORY
    value: "/recordings"
  - name: DB_URL
    value: "jdbc:oracle:thin:@uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com:1581/LRD"
  - name: DB_USERNAME
    value: "operationaldb"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: S3_MOUNT_PATH
    value: "voicecall"
  - name: "THREAD_STALL_SEC"
    value: "600"
  - name: ALERT_TOPIC
    value: "LRD.Alerts.Alert"
  - name: MEMORY_LIMIT
    value: "300"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: THREAD_STALL_SAMPLE_INTERVAL_MS
    value: "10000"
  - name: ISLEASEENABLE
    value: "true"
  - name: MSTR_FILE_MOVE_ENABLE
    value: "true"
  - name: MSTR_REPORT_SOURCE_FOLDER
    value: "/lrd-san/subscription"
  - name: MSTR_REPORT_DEST_FOLDER
    value: "/lrd-backup"
  - name: CUSTOMER
    value: "LTA"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: S3_CHECK_INTERVAL_MINS
    value: "10"

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: lrd-fsxtos3
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: lrd-fsxtos3
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: lrd-fsxtos3-sa
        namespace: lrd-fsxtos3
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-fsxtos3-recordings-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-fsxtos3-recordings-fsx-pv
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-fsxtos3-voicecall-s3-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-fsxtos3-voicecall-s3-pv
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-fsxtos3-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-fsxtos3-san-fsx-pv
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-fsxtos3-san-s3-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: ""
      volumeName: lrd-fsxtos3-san-s3-pv

serviceAccount:
  create: true
  name: lrd-fsxtos3-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-LRD

extraVolumes:
  - name: s3-data
    persistentVolumeClaim:
      claimName: lrd-fsxtos3-voicecall-s3-pvc
  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-fsxtos3-recordings-fsx-pvc
  - name: san-s3-data
    persistentVolumeClaim:
      claimName: lrd-fsxtos3-san-s3-pvc
  - name: san-fsx-data
    persistentVolumeClaim:
      claimName: lrd-fsxtos3-san-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-fsxtos3-spc"
      
extraVolumeMounts:
  - name: s3-data
    mountPath: "/voicecall"
  - name: fsx-data
    mountPath: "/recordings"
  - name: san-s3-data
    mountPath: "/lrd-backup"
  - name: san-fsx-data
    mountPath: "/lrd-san"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-fsxtos3.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-fsxtos3.fms-uat.itfs.lta.gov.sg
      secretName: lrd-fsxtos3-tls