extraEnvs:
  - name: JAVA_OPTS
    value: "-Dspring.profiles.active=dev,vehicle,vehiclestatuses,blocktiminginfo,driversession -Dcom.sun.management.jmxremote.port=9110 -Dcom.sun.management.jmxremote.rmi.port=9110 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dvisualvm.display.name=ClientProxy"
  - name: KEYCLOAK_CLIENT_ID
    value: "clientproxy"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KEYCLOAK_CLIENT_SECRET
  - name: CONFIG_SERVICE_URL
    value: "https://config-api.fms-uat.itfs.lta.gov.sg"
  - name: DATABASE__MONGO__HOST
    value: "uat-app-mongo-mongo1.fms-uat.itfs.lta.gov.sg:27817,uat-app-mongo-mongo2.fms-uat.itfs.lta.gov.sg:27817,uat-app-mongo-mongo3.fms-uat.itfs.lta.gov.sg:27817"
  - name: DATABASE__MONGO__USER
    value: "lio"
  - name: DATABASE__MONGO__PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: MONGO_DB_PASS
  - name: DATABASE__MONGO__PARAMETERS
    value: "authSource=admin&authMechanism=SCRAM-SHA-256"
  - name: MHCC_ENVIRONMENT
    value: "lta_uat_cloud"
  - name: KEYCLOAK_WELLKNOWN_URI
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg/realms/LIO/.well-known/openid-configuration"
  - name: KEYCLOAK_CLIENT_SCOPE
    value: configurationService
  - name: TZ
    value: "Asia/Singapore"
  - name: CLIENTPROXY_WEBVIEW_DISABLEADAPTATION
    value: "true"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9
    alb.ingress.kubernetes.io/healthcheck-path: "/actuator/health/readiness"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: clientproxy.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific     
  tls:
    - hosts:
        - clientproxy.fms-uat.itfs.lta.gov.sg
      secretName: clientproxy-tls

grpcIngress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/success-codes: "200,415"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: clientproxy-grpc.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: clientproxy-java
              port:
                number: 6569
  tls:
    - hosts:
        - clientproxy-grpc.fms-uat.itfs.lta.gov.sg
      secretName: clientproxy-grpc-tls

serviceAccount:
  create: true
  name: clientproxy-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-CLIENTPROXY