extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: CASSANDRA_IP
    value: ""
  - name: CASSANDRA_HOSTNAME
    value: "cassandra.ap-southeast-1.amazonaws.com"
  - name: CASSANDRA_PORT
    value: "9142"
  - name: CASSANDRA_DATACENTER
    value: "ap-southeast-1"
  - name: CASSANDRA_DB_TYPE
    value: "amazon_keyspace"
  - name: CASSANDRA_KEYSPACE
    value: "UAT_APP_KEYSPACE"
  - name: CASSANDRA_USERNAME
    value: "UAT-IAMU-KEYSPACE-at-381491900351"
  - name: CASSANDRA_PASSWORD
    value: "qkyhWbeN523rLG7xw5pt5h7atgP1j1JH2yucDJ0opuUiYmUAFUvP/FVlPro="
  - name: AWS_REGION
    value: "ap-southeast-1"
  - name: KAFKA_SERVER
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_TOPIC_ACTUALDRIVINGDWELL
    value: "Driving_DwellTime"
  - name: KAFKA_TOPIC_REALTIMEMODEL
    value: "Real_Time_Model_Trained"
  - name: PREDICTIONAPI_NATS_URL
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: GRIDTYPE_ID
    value: "500"
  - name: LATITUDE_MAX
    value: "55.636"
  - name: LATITUDE_MIN
    value: "51.222"
  - name: LONGITUDE_MAX
    value: "-5.6582363"
  - name: LONGITUDE_MIN
    value: "-11.0133788"
  - name: WEATHER_API_KEY
    value: "ac43a511d89f6109d335dc5a8c2ba438"
  - name: PS_WEATHERSERVICE_LOGFILE
    value: "/app/DrivingDwellTimePredictionLogs/BaseModels/WeatherService"
  - name: KAFKA_PRODUCER_USERNAME
    value: "realtimeapp"
  - name: KAFKA_PRODUCER_PASSWORD
    value: "yh/qgGxhP+O7R+g2aQ8jWI47G+Y8HRaeHoLZISP9E+s="
  - name: REALTIME_MODEL_FOLDER_DRIVING
    value: "/san/new_py/StoppointLink_Models/RTModels/DrivingTime"
  - name: REALTIME_MODEL_FOLDER_DWELL
    value: "/san/new_py/StoppointLink_Models/RTModels/DwellTime"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: NATS_ALERT_SUBJECT
    value: "NTA_PROD_CLOUD.AIML.Alerts.Alert"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    value: "weatherinsert"
  - name: OTEL_SERVICE_NAME
    value: "weatherinsert"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: KAFKA_THRESHOLD_MINUTES
    value: "60"
  - name: MEMORY_THRESHOLD_MB
    value: "1800"
  - name: HEARTBEAT_THRESHOLD_MINS 
    value: "10"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: weatherinsert.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - weatherinsert.fms-uat.itfs.lta.gov.sg
      secretName: weatherinsert-tls

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: weatherinsert-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: weatherinsert-san-fsx-pv

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: weatherinsert-san-fsx-pvc

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/san"

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
