apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ddm-backend-spc # keep -spc suffix
  namespace: ddm-backend
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-DDMPRD"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: password-alias
          - path: username
            objectAlias: username-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: username
          objectName: username-alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque