image:
  repository: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/geoserver

extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: POSTGRESQL_HOST
    value: "prd-app-pgsql-pgsqldb.cluster-cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: POSTGRESQL_PORT
    value: "5482"
  - name: POSTGRESQL_USER
    value: "gis"
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: GEOSERVER_PASSWORD
  - name: GEOSERVER_BASE_URL
    value: "geoserver.fms.itfs.lta.gov.sg"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png"
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-08b5165e42765ab7d # PRD-APP-INTRA-EKS-APP-SG-ALB-EKS
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
  hosts:
    - host: geoserver.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - geoserver.fms.itfs.lta.gov.sg
      secretName: geoserver-tls

serviceAccount:
  create: true
  name: geoserver-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-GEOSERVER
