extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: POSTGRESQL_HOST
    value: "uat-app-aurora-pgsql-pgsqldb.cluster-cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com"
  - name: POSTGRESQL_PORT
    value: "5482"
  - name: POSTGRESQL_USER
    value: "gis"
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: GEOSERVER_PASSWORD
  - name: GEOSERVER_BASE_URL
    value: "geoserver.fms-uat.itfs.lta.gov.sg"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-1:381491900351:certificate/b065c86f-3713-4066-af5f-a3fd42387339"
  hosts:
    - host: geoserver.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - geoserver.fms-uat.itfs.lta.gov.sg
      secretName: geoserver-tls

serviceAccount:
  create: true
  name: geoserver-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-GEOSERVER
