replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/dispatcherclientweb
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 150Mi

livenessProbe: null

readinessProbe: null
