replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/downlinkconnector
  tag: 2.10.1
  pullPolicy: IfNotPresent

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
    
livenessProbe:
  exec:
    command:
      - sh
      - -c
      - "find /app/healthcheck.liveness -mmin -1"
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "find /app/healthcheck.readiness -mmin -1"
  initialDelaySeconds: 10
  periodSeconds: 20

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "downlinkconnector-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/certs
    readOnly: true

nodeSelector:
  karpenter.sh/nodepool: application-node-pool