apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: downlinkconnector-spc # keep -spc suffix
  namespace: downlinkconnector
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "PRD-EMQX-DOWNLINK-CLIENT-PEM"
        objectType: "secretsmanager"
      - objectName: "PRD-EMQX-DOWNLINK-CLIENT-KEY"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: downlinkconnector-secrets
      type: Opaque
      data:
        - objectName: "PRD-EMQX-DOWNLINK-CLIENT-PEM"
          key: PRD-EMQX-DOWNLINK-CLIENT-PEM
        - objectName: "PRD-EMQX-DOWNLINK-CLIENT-KEY"
          key: PRD-EMQX-DOWNLINK-CLIENT-KEY