apiVersion: v1
kind: Service
metadata:
  name: nats-metrics-service
  namespace: "nats"
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
    deployedAsPartOf: kps
    release: "kps"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8222
      protocol: TCP
      targetPort: 8222
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats