apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: config-api-spc # keep -spc suffix
  namespace: config-api
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "UAT-APP-EKS-CONFIGURATIONSERVICE"
        objectType: "secretsmanager"
        jmesPath:
          - path: KEYCLOAK_CLIENT_SECRET
            objectAlias: KEYCLOAK_CLIENT_SECRET-alias
      - objectName: "UAT-CONFIG-API-DB"
        objectType: "secretsmanager"
        jmesPath:
          - path: CONFIG_API_PASSWORD
            objectAlias: CONFIG_API_PASSWORD-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: KEYCLOAK_CLIENT_SECRET # key whose corresponding value will have content of the secret
          objectName: KEYCLOAK_CLIENT_SECRET-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: CONFIG_API_PASSWORD # key whose corresponding value will have content of the secret
          objectName: CONFIG_API_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque
