global:
  imageRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/docker.io

externalDatabase:
  host: uat-app-aurora-pgsql-pgsqldb.cluster-cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com
  port: 5482
  database: keycloak
  user: keycloak_user
  existingSecret: keycloak-password
  existingSecretPasswordKey: password

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5

extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KC_CACHE_STACK
    value: kubernetes
  - name: JAVA_OPTS_APPEND
    value: "-Xms1024m -Xmx2048m -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local -Djavax.net.ssl.trustStore=/cacerts-shared/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true"
    #-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true
    #[Root exception is javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching FMS-UAT.ITFS.LTA.GOV.SG found.]
  # - name: KEYCLOAK_EXTRA_ARGS
  #   value: "--import-realm"
  # - name: KEYCLOAK_IMPORT
  #   value: "/opt/bitnami/keycloak/data/import/realm.json"
  - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY #  WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
    value: "true"
  - name: KC_LOG_LEVEL
    value: INFO
  - name: TZ
    value: Asia/Singapore
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_HOSTNAME_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://keycloak.fms-uat.itfs.lta.gov.sg"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
    value: "false"
  - name: KC_HOSTNAME_STRICT_BACKCHANNEL
    value: "true"
  - name: KC_PROXY
    value: "edge"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"

proxy: edge
cache:
  enabled: true

resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"

ingress:
  enabled: true
  ingressClassName: alb-internal-app
  hostname: keycloak-app.fms-uat.itfs.lta.gov.sg
  path: /*
  pathType: ImplementationSpecific
  tls: false
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/health/ready"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c

adminIngress:
  enabled: false
  ingressClassName: alb-internal-app
  hostname: keycloak-app-admin.fms-uat.itfs.lta.gov.sg
  path: /
  pathType: Prefix
  tls: false
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/health/ready"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c

serviceAccount:
  create: true
  name: keycloak-sa
  namespace: keycloak
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-ACTIONMANAGER #temp

initContainers:
  - name: import-ldap-cert
    image: "{{ .Values.global.imageRegistry }}/bitnami/keycloak:23.0.7-debian-12-r3"
    command:
      - sh
      - -c
      - |
        cp /opt/java/openjdk/lib/security/cacerts /cacerts-shared/cacerts
        for cert in /certs/*.crt /certs/*.pem; do
          [ -f "$cert" ] && keytool -import -trustcacerts -alias ldap-cert-$(basename $cert) -file $cert -keystore /cacerts-shared/cacerts -storepass changeit -noprompt || true
        done
    volumeMounts:
      - name: keycloak-cert-volume
        mountPath: /certs
        readOnly: true
      - name: cacerts-volume
        mountPath: /cacerts-shared

extraVolumes:
  - name: cacerts-volume
    emptyDir: {}
  - name: keycloak-cert-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "keycloak-cert-spc"
  - name: keycloak-password-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "keycloak-password-spc"
extraVolumeMounts:
  - name: cacerts-volume
    mountPath: /cacerts-shared
  - name: keycloak-cert-volume
    mountPath: /opt/bitnami/keycloak/truststore/
    readOnly: true
  - name: keycloak-password-volume
    mountPath: /opt/bitnami/keycloak/secrets/
    readOnly: true