replicaCount: 2

image:
  repository: 381491900351.dkr.ecr.eu-west-1.amazonaws.com/lrd-busdispatchdataentry
  tag: 1.1.6
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: "/healthz"
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/readyz"
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 60
  successThreshold: 1
  failureThreshold: 3