apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-busdispatchdataentry-spc # keep -spc suffix
  namespace: lrd-busdispatchdataentry
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-BI_OPERATIONALDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_OPERATIONALDB_USERNAME-alias        
          - path: password
            objectAlias: BI_OPERATIONALDB_PASSWORD-alias
      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-LRD"
        objectType: "secretsmanager"
        jmesPath:
              - path: username
                objectAlias: KAFKA_USERNAME-alias
              - path: password
                objectAlias: KAFKA_PASSWORD-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: BI_OPERATIONALDB_USERNAME
          objectName: BI_OPERATIONALDB_USERNAME-alias
        - key: BI_OPERATIONALDB_PASSWORD
          objectName: BI_OPERATIONALDB_PASSWORD-alias
        - key: KAFKA_USERNAME # key whose corresponding value will have content of the secret
          objectName: KAFKA_USERNAME-alias
        - key: KAFKA_PASSWORD # key whose corresponding value will have content of the secret
          objectName: KAFKA_PASSWORD-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque
