image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-ccrtdeactivatetransfer

extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: KAFKA_SERVER
    value: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_MESSAGE_MAX_CONSUME_LIMIT
    value: "1000"
  - name: DEACTIVATE_TRANSFER_TOPIC
    value: "cc_lrd_deactivatetransfer"
  - name: KAFKA_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_USERNAME
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: DB_SID
    value: "LRD"
  - name: DB_DATABASEMACHINEIP
    value: "prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: DB_BIDB_USER
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BIDB_USERNAME
  - name: DB_BIDB_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BIDB_PASSWORD
  - name: DB_BIDB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_USERNAME
  - name: DB_BIDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_PASSWORD
  - name: DB_DSDB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSDB_USERNAME
  - name: DB_DSDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSDB_PASSWORD
  - name: DB_DSLIODB_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSLIODB_USERNAME
  - name: DB_DSLIODB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_DSLIODB_PASSWORD
  - name: DB_OPERATIONAL_USER_APP
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_OPERATIONALDB_USERNAME
  - name: DB_OPERATIONALDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_OPERATIONALDB_PASSWORD
  - name: DB_PORT
    value: "1581"
  - name: DB_CONNECTION_TIMEOUT
    value: "120"
  - name: DB_DRIVER_NAME
    value: "oracle.jdbc.driver.OracleDriver"
  - name: DB_MAX_ACTIVE_CONNECTIONS
    value: "40"
  - name: DB_MAX_IDLE_CONNECTIONS
    value: "0"
  - name: DB_MAX_WAIT_TIME
    value: "30000"
  - name: "THREAD_STALL_SEC"
    value: "600"
  - name: ALERT_TOPIC
    value: "LRD.Alerts.Alert"
  - name: MEMORY_LIMIT
    value: "300"
  - name: NATS_SERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: THREAD_STALL_SAMPLE_INTERVAL_SEC
    value: "10000"

serviceAccount:
  create: true
  name: lrd-ccrtdeactivatetransfer-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-LRD

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-ccrtdeactivatetransfer-spc"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-ccrtdeactivatetransfer.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-ccrtdeactivatetransfer.fms.itfs.lta.gov.sg
      secretName: lrd-ccrtdeactivatetransfer-tls

keda:
  enabled: true
  secret:
    existingSecret: "aws-secrets-manager-secret"
    usernameKey: "KAFKA_USERNAME"
    passwordKey: "KAFKA_PASSWORD"
    sasl: "scram_sha512"
    tls: "enable"
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
          consumerGroup: "CCRealTimeDeactivateTransfer"
          topic: "cc_lrd_deactivatetransfer"
          lagThreshold: "10000"