apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: aws-signer-plugin
  namespace: gatekeeper
spec:
  name: notation-com.amazonaws.signer.notation.plugin
  artifactTypes: application/vnd.oci.image.manifest.v1+json
  source:
    artifact: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/public.ecr.aws/aws-signer/notation-plugin:linux-amd64-latest
    authProvider:
      name: awsEcrBasic
