environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../global.yaml
  - ../app.yaml

releases:
  - name: ratify
    installed: true
    namespace: gatekeeper
    chart: ecr-uat-helm-charts/ratify
    version: 1.15.0
    values:
      # - default.values.yaml
      - "{{ .Environment.Name }}.values.yaml"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "crds/"
          - "--context"
          - "{{.Environment.KubeContext}}"
