apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-safparser-spc # keep -spc suffix
  namespace: lrd-safparser
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-BIDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BIDB_USERNAME-alias        
          - path: password
            objectAlias: BIDB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-BI_BIDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_BIDB_USERNAME-alias        
          - path: password
            objectAlias: BI_BIDB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-BI_DSDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_DSDB_USERNAME-alias        
          - path: password
            objectAlias: BI_DSDB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-BI_DSLIODB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_DSLIODB_USERNAME-alias        
          - path: password
            objectAlias: BI_DSLIODB_PASSWORD-alias

      - objectName: "PRD-APP-RDS-ORACLE-BI_OPERATIONALDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_OPERATIONALDB_USERNAME-alias        
          - path: password
            objectAlias: BI_OPERATIONALDB_PASSWORD-alias
  secretObjects:
    - data:
        - key: BIDB_USERNAME
          objectName: BIDB_USERNAME-alias
        - key: BIDB_PASSWORD
          objectName: BIDB_PASSWORD-alias

        - key: BI_BIDB_USERNAME
          objectName: BI_BIDB_USERNAME-alias
        - key: BI_BIDB_PASSWORD
          objectName: BI_BIDB_PASSWORD-alias

        - key: BI_DSDB_USERNAME
          objectName: BI_DSDB_USERNAME-alias
        - key: BI_DSDB_PASSWORD
          objectName: BI_DSDB_PASSWORD-alias

        - key: BI_DSLIODB_USERNAME
          objectName: BI_DSLIODB_USERNAME-alias
        - key: BI_DSLIODB_PASSWORD
          objectName: BI_DSLIODB_PASSWORD-alias

        - key: BI_OPERATIONALDB_USERNAME
          objectName: BI_OPERATIONALDB_USERNAME-alias
        - key: BI_OPERATIONALDB_PASSWORD
          objectName: BI_OPERATIONALDB_PASSWORD-alias
      secretName: aws-secrets-manager-secret
      type: Opaque