apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kps
  name: ingress-nginx-service-monitor
  namespace: observability
spec:
  endpoints:
  - port: metrics
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
    - ingress-nginx-internal
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      ismetricservice: "true"
