image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-applatency

extraEnvs:
  - name: KAFKA_SERVER
    value: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: ORACLE_DATABASE_MACHINE_IP
    value: "prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: ORACLE_PORT
    value: "1581"
  - name: KAFKA_TOPIC_LATENCY
    value: "monitoring-trace-latency"
  - name: ORACLE_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_USERNAME
  - name: ORACLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: BI_BIDB_PASSWORD
  - name: ORACLE_SERVICE_NAME
    value: "LRD"
  - name: KAFKA_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_USERNAME
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: TZ
    value: "Asia/Singapore"
  - name: HEARTBEAT_THRESHOLD_MINS
    value: "10"
  - name: MEMORY_THRESHOLD_MB
    value: "1500"
  - name: NATS_SERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-applatency.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-applatency.fms.itfs.lta.gov.sg
      secretName: lrd-applatency-tls

serviceAccount:
  create: true
  name: lrd-applatency-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-LRD
  
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-applatency-spc"
        
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

keda:
  enabled: true
  secret:
    existingSecret: "aws-secrets-manager-secret"
    usernameKey: "KAFKA_USERNAME"
    passwordKey: "KAFKA_PASSWORD"
    sasl: "scram_sha512"
    tls: "enable"
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: "b-1.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096,b-2.prdappmskmskclust.gvgf64.c4.kafka.ap-southeast-1.amazonaws.com:9096"
          consumerGroup: "latency"
          topic: "monitoring-trace-latency"
          lagThreshold: "10000"