apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-applatency-spc
  namespace: lrd-applatency
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-BI_BIDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_BIDB_USERNAME-alias        
          - path: password
            objectAlias: BI_BIDB_PASSWORD-alias

      - objectName: "AmazonMSK_PRD-SECRET-KAFKA-LRD"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: KAFKA_USERNAME-alias        
          - path: password
            objectAlias: KAFKA_PASSWORD-alias
  secretObjects:
    - data:
        - key: BI_BIDB_USERNAME
          objectName: BI_BIDB_USERNAME-alias
        - key: BI_BIDB_PASSWORD
          objectName: BI_BIDB_PASSWORD-alias
          
        - key: KAFKA_PASSWORD
          objectName: KAFKA_PASSWORD-alias
        - key: KAFKA_USERNAME
          objectName: KAFKA_USERNAME-alias
      secretName: aws-secrets-manager-secret
      type: Opaque
