environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../../global.yaml
  - ../../app.yaml
releases:
  - name: keda
    namespace: keda
    createNamespace: true
    chart: ecr-uat-helm-charts/kedacore/keda
    version: 2.19.0
    values:
      - default.values.yaml
      - {{ .Environment.Name }}.values.yaml