image:
  pullPolicy: IfNotPresent
  keda:
    registry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: ghcr.io/kedacore/keda
    tag: 2.19.0
  metricsApiServer:
    registry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: ghcr.io/kedacore/keda-metrics-apiserver
    tag: 2.19.0
  webhooks:
    registry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: ghcr.io/kedacore/keda-admission-webhooks
    tag: 2.19.0

global:
  image:
    registry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com