replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/modeladapter
  tag: 1.12.10
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8050

resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 1
    memory: 3Gi

podDisruptionBudget:
  enabled: true
  maxUnavailable: 0 

livenessProbe:
  httpGet:
    path: "/actuator/health/liveness"
    port: 8050
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 180
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: "/actuator/health/readiness"
    port: 8050
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 180
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 5

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "modeladapter-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

nodeSelector:
  karpenter.sh/nodepool: application-node-pool