image:
  repository: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/modeladapter

extraEnvs:
  - name: JAVA_OPTS
    value: "-Dspring.profiles.active=vehicle,vehiclestatuses,blocktiminginfo,driversession,dpitexttable,stopName,stop -Dcom.sun.management.jmxremote.port=9110 -Dcom.sun.management.jmxremote.rmi.port=9110 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dvisualvm.display.name=ModelAdapter"
  - name: KEYCLOAK_CLIENT_ID
    value: "modeladapter"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KEYCLOAK_CLIENT_SECRET
  - name: CONFIG_SERVICE_URL
    value: "https://config-api.fms.itfs.lta.gov.sg"
  - name:  MHCC_ENVIRONMENT
    value: "lta_prod_cloud"
  - name: KEYCLOAK_WELLKNOWN_URI
    value: "https://keycloak.fms.itfs.lta.gov.sg/realms/LIO/.well-known/openid-configuration"
  - name: KEYCLOAK_CLIENT_SCOPE
    value: configurationService
  - name: DATABASE__MONGO__HOST
    value: "prd-app-mongo-mongo1.fms.itfs.lta.gov.sg:27817,prd-app-mongo-mongo2.fms.itfs.lta.gov.sg:27817,prd-app-mongo-mongo3.fms.itfs.lta.gov.sg:27817"
  - name: DATABASE__MONGO__USER
    value: "lio"
  - name: DATABASE__MONGO__PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: MONGO_DB_PASS
  - name: DATABASE__MONGO__PARAMETERS
    value: "authSource=admin&authMechanism=SCRAM-SHA-256"
  - name: TZ
    value: "Asia/Singapore"

ingress:
  enabled: true
  className: alb-internal-app
  hosts:
    - host: modeladapter.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - modeladapter.fms.itfs.lta.gov.sg
      secretName: modeladapter-tls
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/actuator/health/readiness"
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-08b5165e42765ab7d
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e

serviceAccount:
  create: true
  name: modeladapter-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-MODELADAPTER

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi