apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-mapanalytics-spc # keep -spc suffix
  namespace: lrd-mapanalytics
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-BI_BIDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: BI_BIDB_USERNAME-alias        
          - path: password
            objectAlias: BI_BIDB_PASSWORD-alias

      - objectName: "PRD-KEYCLOAK-CLIENT-MTV"
        objectType: "secretsmanager"
        jmesPath:
          - path: client_id
            objectAlias: MTV_CLIENT_ID-alias        
          - path: client_secret
            objectAlias: MTV_CLIENT_SECRET-alias
  secretObjects:
    - data:
        - key: BI_BIDB_USERNAME
          objectName: BI_BIDB_USERNAME-alias
        - key: BI_BIDB_PASSWORD
          objectName: BI_BIDB_PASSWORD-alias

        - key: MTV_CLIENT_ID
          objectName: MTV_CLIENT_ID-alias
        - key: MTV_CLIENT_SECRET
          objectName: MTV_CLIENT_SECRET-alias
      secretName: aws-secrets-manager-secret
      type: Opaque