replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/actionmanager
  tag: 3.17.26
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8090
  extraPorts:
    - port: 6568
      name: grpc
extraContainerPorts:
  - name: grpc
    containerPort: 6568

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
    
livenessProbe:
  httpGet:
    path: "/actuator/health/liveness"
    port: 8090
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 180
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/actuator/health/readiness"
    port: 8090
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 210
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "actionmanager-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
  
nodeSelector:
  karpenter.sh/nodepool: application-node-pool