apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: actionmanager-spc # keep -spc suffix
  namespace: actionmanager
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-KEYCLOAK-CLIENT-ACTIONMANAGER"
        objectType: "secretsmanager"
        jmesPath:
          - path: client_secret
            objectAlias: KEYCLOAK_CLIENT_SECRET-alias
      - objectName: "PRD-APP-MONGO-LIO"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: MONGO_DB_PASS-alias
  secretObjects:
    - data:
        - key: KEYCLOAK_CLIENT_SECRET
          objectName: KEYCLOAK_CLIENT_SECRET-alias
        - key: MONGO_DB_PASS
          objectName: MONGO_DB_PASS-alias
      secretName: aws-secrets-manager-secret
      type: Opaque
