kind: DaemonSet

replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/fluent-bit
  tag: 4.1.2
  digest:
  pullPolicy: IfNotPresent

testFramework:
  enabled: true
  namespace:
  image:
    repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/library/busybox
    pullPolicy: Always
    tag: 1.37.0
    digest:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:
  automountServiceAccountToken:

rbac:
  create: true
  nodeAccess: false
  eventsAccess: false

podSecurityPolicy:
  create: false
  annotations: {}
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny

openShift:
  enabled: false
  securityContextConstraints:
    create: true
    name: ""
    annotations: {}
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: MustRunAs
    existingName: ""

podSecurityContext: {}

hostNetwork: false
dnsPolicy: ClusterFirst

dnsConfig: {}

hostAliases: []

securityContext: {}

service:
  type: ClusterIP
  port: 2020
  internalTrafficPolicy:
  loadBalancerClass:
  loadBalancerSourceRanges: []
  loadBalancerIP:
  labels: {}
  annotations: {}
  externalIPs: []

serviceMonitor:
  enabled: false

  additionalEndpoints: []

prometheusRule:
  enabled: false

dashboards:
  enabled: false
  labelKey: grafana_dashboard
  labelValue: 1
  annotations: {}
  namespace: ""
  deterministicUid: false

lifecycle: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http

resources:
  limits:
    cpu: 600m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  extraHosts: []
  tls: []

autoscaling:
  vpa:
    enabled: false

    annotations: {}

    controlledResources: []

    controlledValues:

    maxAllowed: {}
    minAllowed: {}

    updatePolicy:
      updateMode: Auto

  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  customRules: []
  behavior: {}

podDisruptionBudget:
  enabled: false
  annotations: {}
  maxUnavailable: "30%"

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

annotations: {}

podAnnotations: {}

podLabels: {}

minReadySeconds:

terminationGracePeriodSeconds:

priorityClassName: ""

envWithTpl: []

envFrom: []

extraContainers: []

flush: 1

metricsPort: 2020

extraPorts:
  - port: 9880
    containerPort: 9880
    protocol: TCP
    name: http-ingest

extraVolumes: []

extraVolumeMounts: []

updateStrategy: {}

existingConfigMap: ""

networkPolicy:
  enabled: false

luaScripts: {}

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 900MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [INPUT]
        Name forward
        Listen 0.0.0.0
        Port 24224

    [INPUT]
        Name http
        Port 9880

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
        Labels Off
        Annotations Off

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix k8s_

    [FILTER]
        Name grep
        Match kube.*
        Exclude k8s_namespace_name fluentbit
        Exclude k8s_namespace_name logs-explorer

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host vpc-uat-cs-opensearch-domain-5e2bwiz57e5jnd7dqsvycanh7u.ap-southeast-1.es.amazonaws.com
        Port 443
        HTTP_User ${OPENSEARCH_USERNAME}
        HTTP_Passwd ${OPENSEARCH_PASSWORD}
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix logs-fluentbit
        Logstash_DateFormat %Y.%m.%d
        Suppress_Type_Name On
        Retry_Limit False
        Trace_Error On
        Trace_Output On

    [OUTPUT]
        Name es
        Match host.*
        Host vpc-uat-cs-opensearch-domain-5e2bwiz57e5jnd7dqsvycanh7u.ap-southeast-1.es.amazonaws.com
        Port 443
        HTTP_User ${OPENSEARCH_USERNAME}
        HTTP_Passwd ${OPENSEARCH_PASSWORD}
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix logs-fluentbit
        Logstash_DateFormat %Y.%m.%d
        Suppress_Type_Name On
        Retry_Limit False
        Trace_Error On
        Trace_Output On

  upstream: {}

  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  extraFiles: {}

volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/conf

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true

command:
  - /fluent-bit/bin/fluent-bit

args:
  - --workdir=/fluent-bit/etc
  - --config=/fluent-bit/etc/conf/fluent-bit.conf

initContainers: []

logLevel: info

hotReload:
  enabled: false
  image:
    repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/configmap-reload
    tag: v0.15.0
    digest:
    pullPolicy: IfNotPresent
  resources: {}
  extraWatchVolumes: []