extraEnvs:
  - name: TZ
    value: "Asia/Singapore"
  - name: KAFKA_SERVER
    value: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
  - name: KAFKA_MESSAGE_MAX_CONSUME_LIMIT
    value: "1"
  - name: SIGNAL_TOPIC
    value: "cc_lrd_signals"
  - name: LOCAL_CACHE_URL
    value: "https://lrd-cache.fms-uat.itfs.lta.gov.sg/v1/"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: NATS_REPLICAS
    value: "3"
  - name: CACHE_STREAM_NAME
    value: "CacheUpdatedStream"
  - name: CACHE_SUBJECT_NAME
    value: "CacheUpdated"
  - name: NATS_RETENTION_MESSAGE_DAYS
    value: "7"
  - name: KAFKA_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_USERNAME
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: KAFKA_PASSWORD
  - name: DB_SID
    value: "LRD"
  - name: DB_DATABASEMACHINEIP
    value: "uat-app-aurora-oracle-oracledb.cjyyk4aoo8q7.ap-southeast-1.rds.amazonaws.com"
  - name: DB_BIDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_BIDB_USER
    value: "BIDB"
  - name: DB_BIDB_USER_APP
    value: "BI_BIDB"
  - name: DB_DSDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSDB_USER_APP
    value: "BI_DSDB"
  - name: DB_DSLIODB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_DSLIODB_USER_APP
    value: "BI_DSLIODB"
  - name: DB_OPERATIONALDB_APP_PWD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: LRD_PASSWORD
  - name: DB_OPERATIONAL_USER_APP
    value: "BI_OPERATIONALDB"
  - name: DB_PORT
    value: "1581"
  - name: DB_CONNECTION_TIMEOUT
    value: "120"
  - name: DB_DRIVER_NAME
    value: "oracle.jdbc.driver.OracleDriver"
  - name: DB_MAX_ACTIVE_CONNECTIONS
    value: "40"
  - name: DB_MAX_IDLE_CONNECTIONS
    value: "0"
  - name: DB_MAX_WAIT_TIME
    value: "30000"
  - name: VEHICLE_POSITION_URL
    value: "https://rtvehicleposition.fms-uat.itfs.lta.gov.sg/get-history-data"
  - name: "THREAD_STALL_SEC"
    value: "600"
  - name: ALERT_TOPIC
    value: "LRD.Alerts.Alert"
  - name: MEMORY_LIMIT
    value: "300"
  - name: BUFFER_MINS
    value: "15"
  - name: THREAD_STALL_SAMPLE_INTERVAL_MS
    value: "10000"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

serviceAccount:
  create: true
  name: lrd-ccrealtimesignals-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-LRD

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "lrd-ccrealtimesignals-spc"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-ccrealtimesignals.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-ccrealtimesignals.fms-uat.itfs.lta.gov.sg
      secretName: lrd-ccrealtimesignals-tls

keda:
  enabled: true
  secret:
    existingSecret: "aws-secrets-manager-secret"
    usernameKey: "KAFKA_USERNAME"
    passwordKey: "KAFKA_PASSWORD"
    sasl: "scram_sha512"
    tls: "enable"
  scaledObject:
    minReplicas: 1
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: "b-1.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096,b-2.uatappmskmskclust.kkfygc.c5.kafka.ap-southeast-1.amazonaws.com:9096"
          consumerGroup: "CCRealTimeSignals"
          topic: "cc_lrd_signals"
          # lagThreshold: "10000"
          lagThreshold: "3000"