mode: "deployment"
namespaceOverride: "opentelemetry"
replicaCount: 1

presets:
  logsCollection:
    enabled: false
    includeCollectorLogs: false
    storeCheckpoints: false
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: false
    extractAllPodAnnotations: false
  kubeletMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
  clusterMetrics:
    enabled: true

configMap:
  create: true
  existingName: ""

config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
  processors:
    attributes/add_labels:
      actions:
        - key: via
          value: opentelemetry-collector
          action: insert
    deltatocumulative:
        max_stale: 5m
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          cors:
            allowed_origins:
            - http://*
            - https://*
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 15s
            static_configs:
              - targets:
                  - localhost:8888
  service:
    telemetry:
      metrics:
        readers:
          - pull:
              exporter:
                prometheus:
                  host: localhost
                  port: 8888
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - otlphttp/all
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - otlphttp/all
        processors:
          - memory_limiter
          - batch
          - deltatocumulative
          - attributes/add_labels
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlphttp/all
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

useGOMEMLIMIT: true

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  httpGet:
    port: 13133
    path: /

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  httpGet:
    port: 13133
    path: /

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: nightly
  digest: ""

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  health-check:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
#   jaeger-compact:
#     enabled: true
#     containerPort: 6831
#     servicePort: 6831
#     hostPort: 6831
#     protocol: UDP
#   jaeger-thrift:
#     enabled: true
#     containerPort: 14268
#     servicePort: 14268
#     hostPort: 14268
#     protocol: TCP
#   jaeger-grpc:
#     enabled: true
#     containerPort: 14250
#     servicePort: 14250
#     hostPort: 14250
#     protocol: TCP
#   zipkin:
#     enabled: true
#     containerPort: 9411
#     servicePort: 9411
#     hostPort: 9411
#     protocol: TCP
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
    