environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../global.yaml
  - ../app.yaml

releases:
  - name: opentelemetry-collector
    installed: true
    namespace: opentelemetry
    chart: ecr-uat-helm-charts/helm/opentelemetry-collector
    version: 0.126.0
    values:
      - default.values.yaml
      - "{{ .Environment.Name }}.values.yaml"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
          - "--context"
          - "{{.Environment.KubeContext}}"