replicaCount: 2

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-dbapi
  tag: 1.7.6
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: "/healthz"
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: "/readyz"
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 60
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5

