apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lrd-dbapi-spc # keep -spc suffix
  namespace: lrd-dbapi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-REPORTINGDB"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: REPORTINGDB_USERNAME-alias        
          - path: password
            objectAlias: REPORTINGDB_PASSWORD-alias
  secretObjects:
    - data:
        - key: REPORTINGDB_USERNAME
          objectName: REPORTINGDB_USERNAME-alias
        - key: REPORTINGDB_PASSWORD
          objectName: REPORTINGDB_PASSWORD-alias
      secretName: aws-secrets-manager-secret
      type: Opaque