replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/uplinkconnector
  tag: 2.12.4
  pullPolicy: Always

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 150Mi

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
   
probeType: exec

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - "find /app/healthcheck.liveness -mmin -1"
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "find /app/healthcheck.readiness -mmin -1"
  initialDelaySeconds: 10
  periodSeconds: 20

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "uplinkconnector-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/certs
    readOnly: true

nodeSelector:
  karpenter.sh/nodepool: application-node-pool