apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: uplinkconnector-spc # keep -spc suffix
  namespace: uplinkconnector
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "PRD-EMQX-UPLINK-CLIENT-PEM"
        objectType: "secretsmanager"
      - objectName: "PRD-EMQX-UPLINK-CLIENT-KEY"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: uplinkconnector-secrets
      type: Opaque
      data:
        - objectName: "PRD-EMQX-UPLINK-CLIENT-PEM"
          key: PRD-EMQX-UPLINK-CLIENT-PEM
        - objectName: "PRD-EMQX-UPLINK-CLIENT-KEY"
          key: PRD-EMQX-UPLINK-CLIENT-KEY
