apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kps-external-dns
  namespace: observability
  labels:
    release: kps
spec:
  jobLabel: "app.kubernetes.io/instance"
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  namespaceSelector:
    matchNames:
      - "external-dns"
  endpoints:
  - port: http
