replicaCount: 1

image:
  repository: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com/timetable-api
  tag: 3.10.7
  pullPolicy: Always

service:
  type: ClusterIP
  port: 19010

grpcService:
  enabled: true
  type: ClusterIP
  port: 9010

resources:
  limits:
    cpu: 1024m
    memory: 8Gi
  requests:
    cpu: 1024m
    memory: 8Gi

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

deployment:
  containerPorts:
    - name: grpc
      port: 9010
    - name: http
      port: 19010

livenessProbe:
  httpGet:
    path: "/health/liveness"
    port: 19010
    scheme: HTTP
  initialDelaySeconds: 240
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/health/readiness"
    port: 19010
    scheme: HTTP
  initialDelaySeconds: 240
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "timetable-api-spc"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

nodeSelector:
  karpenter.sh/nodepool: application-node-pool