apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: timetable-api-spc # keep -spc suffix
  namespace: timetable-api
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "PRD-KEYCLOAK-CLIENT-SCHEDULESERVICE"
        objectType: "secretsmanager"
        jmesPath:
          - path: client_secret
            objectAlias: KEYCLOAK_CLIENT_SECRET-alias
      - objectName: "PRD-APP-MONGO-LIO"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: MONGO_DB_PASS-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: KEYCLOAK_CLIENT_SECRET # key whose corresponding value will have content of the secret
          objectName: KEYCLOAK_CLIENT_SECRET-alias # name of the mounted content to sync. this could be the object name or the object alias
        - key: MONGO_DB_PASS # key whose corresponding value will have content of the secret
          objectName: MONGO_DB_PASS-alias # name of the mounted content to sync. this could be the object name or the object alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque