apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ddm-message-spc # keep -spc suffix
  namespace: ddm-message
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "PRD-APP-RDS-ORACLE-DDMPRD"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: password-alias
          - path: username
            objectAlias: username-alias
      - objectName: "PRD-CA-CRT"
        objectType: "secretsmanager"
      - objectName: "PRD-EMQX-DDM-MESSAGE-CLIENT-PEM"
        objectType: "secretsmanager"
      - objectName: "PRD-EMQX-DDM-MESSAGE-CLIENT-KEY"
        objectType: "secretsmanager"
      - objectName: "PRD-EMQX-API-SECRET-KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: APIKEY
            objectAlias: APIKEY-alias
          - path: SECRETKEY
            objectAlias: SECRETKEY-alias
  secretObjects: # using secret objects require syncSecret.enabled=true else you will get configuration error during deployement
    - data:
        - key: password # key whose corresponding value will have content of the secret
          objectName: password-alias # name of the mounted content to sync. this could be the object name or the object alias
        - objectName: "PRD-CA-CRT"
          key: PRD-CA-CRT
        - objectName: "PRD-EMQX-DDM-MESSAGE-CLIENT-PEM"
          key: PRD-EMQX-DDM-MESSAGE-CLIENT-PEM
        - objectName: "PRD-EMQX-DDM-MESSAGE-CLIENT-KEY"
          key: PRD-EMQX-DDM-MESSAGE-CLIENT-KEY
        - key: username
          objectName: username-alias
        - key: APIKEY
          objectName: APIKEY-alias
        - key: SECRETKEY
          objectName: SECRETKEY-alias
      secretName: aws-secrets-manager-secret # DO NOT CHANGE THIS
      type: Opaque