extraEnvs:
  - name: PROPERTY_JDBC_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: host
  - name: PROPERTY_JDBC_URL
    value: "jdbc:oracle:thin:@$(PROPERTY_JDBC_HOST):1581/DDM"
  - name: PROPERTY_JDBC_USERNAME
    value: "ddmprd"
  - name: PROPERTY_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: PROPERTY_BACKEND_WAIT_INTERVAL
    value: "5"
  - name: PROPERTY_GARAGE_ID
    value: "1001"
  - name: PROPERTY_BACKEND_HTTP_PORT
    value: "8181"
  - name: PROPERTY_DOWNLOAD_OLD_ROOT
    value: "/ddm/storage/downloaddata"
  - name: PROPERTY_DOWNLOAD_NEW_ROOT
    value: "/ddm/download"
  - name: PROPERTY_UPLOAD_NEW_ROOT
    value: "/ddm/upload"
  - name: PROPERTY_UPLOAD_ONDEMAND_ROOT
    value: "/ddm/upload"
  - name: PROPERTY_DOWNLOAD_DEVICE_ROOT
    value: "download/<devicetype>/"
  - name: PROPERTY_ONDEMAND_ENABLE
    value: "1"
  - name: PROPERTY_IS_MQTT_BROKER
    value: "true"
  - name: PROPERTY_MQTT_UPLOAD_TOPIC
    value: "lio/uat/ddm/3/Upload/#"
  - name: PROPERTY_MQTT_DOWNLOAD_TOPIC
    value: "lio/uat/ddm/3/Download/"
  - name: PROPERTY_COMMAND_MESSAGE_ENABLE
    value: "0"
  - name: PROPERTY_COMMAND_MESSAGE_BATCH_ENABLE
    value: "1"
  - name: PROPERTY_BATCH_SIZE
    value: "10"
  - name: PROPERTY_DOWNLOAD_BANDWIDTH_AVERAGE
    value: "400"
  - name: PROPERTY_LOAD_JOB_ENABLE
    value: "1"
  - name: PROPERTY_MQTT_PUBLISHER_ID
    value: "ddmmessageservice"
  - name: PROPERTY_MQTT_URI
    value: "ssl://emqx.fms-uat.itfs.lta.gov.sg:8883"
  - name: PROPERTY_MQTT_SSL_CA_CERT_PATH
    value: "/mnt/secrets-store/UAT-CA-CRT"
  - name: PROPERTY_MQTT_SSL_CLIENT_PUBLIC_PATH
    value: "/mnt/secrets-store/UAT-EMQX-DDM-MESSAGE-CLIENT-PEM"
  - name: PROPERTY_MQTT_SSL_CLIENT_PRIVATE_KEY
    value: "/mnt/secrets-store/UAT-EMQX-DDM-MESSAGE-CLIENT-KEY"
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: NATS_SERVER
    value: "nats://nats.fms-uat.itfs.lta.gov.sg:4222"
  - name: NATS_SUBJECT
    value: "BIETL_VehicleParser"
  - name: NATS_STREAM
    value: "saf-files"
  - name: FILE_EXTRACTION_TIME_IN_MINUTES
    value: "5"
  - name: PROPERTY_FILE_TRANSFER_INTERVAL
    value: "1"
  - name: PROPERTY_COMMAND_MESSAGE_BATCH_CHECK_INTERVAL
    value: "1"
  - name: PROPERTY_EOU_EXTENSIONS
    value: ".saf,.saf.gz"
  - name: PROPERTY_NATS_REPLICA
    value: "3"
  - name: TZ
    value: "Asia/Singapore"
  - name: PROPERTY_ONDEMAND_CHECK_INTERVAL
    value: "5"
  - name: PROPERTY_OTLP_COLLECTOR_URL
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: PROPERTY_OTLP_MESSAGE_SERVICE_NAME
    value: "DDM_MESSAGE_SERVICE"
  - name: PROPERTY_EMQX_API_URL
    value: "https://emqx-dashboard.fms-uat.itfs.lta.gov.sg/api/v5"
  - name: PROPERTY_EMQX_API_USERNAME 
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: APIKEY
  - name: PROPERTY_EMQX_API_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: SECRETKEY
  - name: NATS_SUBJECT_ALERTS
    value: "DDM.Alerts.Alert"
  - name: ENVIRONMENT
    value: "lta"
  - name: DDM_MEMORY_THRESHOLD_MB
    value: "500"
  - name: PROCESSING_MODE
    value: "SingleThreaded"
  - name: PROPERTY_DISCONNECTED_VEHICLE_CONN_STATUS_UPDATE
    value: "2"

serviceAccount:
  create: true
  name: ddm-message-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381491900351:role/UAT-IAMR-EKS-POD-IDENTITY-DDM

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ddm-message-ddm-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: ddm-message-ddm-fsx-pv

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: ddm-message-ddm-fsx-pvc
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "ddm-message-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/ddm"
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
    
ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: uat-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-0e94cb42970e1c3d9
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:381491900351:regional/webacl/UAT-APP-INTRA-EKS-APP-WAF/9f041adc-078f-44f9-88c0-586f18144a2c
  hosts:
    - host: ddm-message.fms-uat.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - ddm-message.fms-uat.itfs.lta.gov.sg
      secretName: ddm-message-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi

keda:
  enabled: true
  secret: {}
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    cooldownPeriod: 5
    triggers:
      - type: metrics-api
        metadata:
          url: "https://ddm-message.fms-uat.itfs.lta.gov.sg"
          valueLocation: "len"
          format: "json"
          targetValue: "100"