image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/lrd-vehicleparser

extraEnvs:
  - name: VEHICLEPARSER_SAFSTAGINGSTATUSSUBJECT
    value: "StagingStatus"
  - name: VEHICLEPARSER_SAFFILEPATHSUBJECT
    value: "SafFilePathSubject"
  - name: VEHICLEPARSER_SAFSTREAMNAME
    value: "SafFiles"
  - name: VEHICLEPARSER_NATSSUBJECT
    value: "BIETL_VehicleParser"
  - name: VEHICLEPARSER_NATSSTREAM
    value: "saf-files"
  - name: VEHICLEPARSER_NATSSERVER
    value: "nats://nats.fms.itfs.lta.gov.sg:4222"
  - name: VEHICLEPARSER_VEHICLEPARSERPATH
    value: "/san/VehicleRecordings"
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: VEHICLEPARSER_SAFFILESPATH
    value: "/san/VehicleRecordings/FilesToProcess"
  - name: VEHICLEPARSER_SUPPORTBISAFLOCATION
    value: "/san/MainETL/vehicleRecordings/FilesToProcess"
  - name: VEHICLEPARSER_SAFFILESOURCE
    value: "nats"
  - name: TZ
    value: "Asia/Singapore"
  - name: VEHICLEPARSER_DISTANCETRAVELLEDTOSTORESPEEDEVENT
    value: "100"
  - name: VEHICLEPARSER_NOFSTOPSCOUNTGREATERTHANVALUE
    value: "1"
  - name: VEHICLEPARSER_SERVICEDAYCD1HRLOWERRANGE
    value: "5"
  - name: VEHICLEPARSER_SERVICEDAYCD1HRUPPERRANGE
    value: "24"
  - name: VEHICLEPARSER_SERVICEDAYCD2HRUPPERRANGE
    value: "2"
  - name: VEHICLEPARSER_TRIPREGISTRATIONASTRIPLOGON
    value: "0"
  - name: VEHICLEPARSER_FILESTOLOADFOLDER
    value: "FilesToLoad"
  - name: VEHICLEPARSER_FILESPROCESSEDFOLDER
    value: "FilesProcessed"
  - name: VEHICLEPARSER_FILESNOTPROCESSEDFOLDER
    value: "FilesNotProcessed"
  - name: VEHICLEPARSER_FILESTOPROCESSFOLDER
    value: "FilesToProcess"
  - name: VEHICLEPARSER_TEMPLOWBRIDGEPATH
    value: "LowBridge"
  - name: VEHICLEPARSER_LOGPATH
    value: "parserlog"
  - name: "THREAD_STALL_THRESHOLD_SECS"
    value: "600"
  - name: NATS_ALERT_SUBJECT
    value: "LRD.Alerts.Alert"
  - name: MEMORY_THRESHOLD_MB
    value: "435"
  - name: TRANSFER_TYPE
    value: "MOVE"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

extraDeploy:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-vehicleparser-ddm-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-vehicleparser-ddm-fsx-pv

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: lrd-vehicleparser-san-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: lrd-vehicleparser-san-fsx-pv
  
extraVolumes:
  - name: fsx-ddmdata
    persistentVolumeClaim:
      claimName: lrd-vehicleparser-ddm-fsx-pvc

  - name: fsx-data
    persistentVolumeClaim:
      claimName: lrd-vehicleparser-san-fsx-pvc

extraVolumeMounts:
  - name: fsx-ddmdata
    mountPath: "/ddm"
  - name: fsx-data
    mountPath: "/san"

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/healthcheck-path: "/readyz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 32k;
  hosts:
    - host: lrd-vehicleparser.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - lrd-vehicleparser.fms.itfs.lta.gov.sg
      secretName: lrd-vehicleparser-tls

keda:
  enabled: true
  secret: {}
  scaledObject:
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 5
    triggers:
      - type: nats-jetstream
        metadata:
          natsServerMonitoringEndpoint: "nats://nats.fms.itfs.lta.gov.sg:8222"
          account: "$G"
          stream: "SafFiles"
          consumer: "vehicle_parser"
          lagThreshold: "10"