replicaCount: 2

image:
  repository: ddm-import
  tag: 1.0.11
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8181

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 150Mi

livenessProbe:
  httpGet:
    path: "/healthz/"
    port: 8181
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 40
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: "/readyz/"
    port: 8181
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 60
  successThreshold: 1
  failureThreshold: 3