environments:
  uat:
    values:
      - ecrRegistry: 381491900351.dkr.ecr.ap-southeast-1.amazonaws.com
  prd:
    values:
      - ecrRegistry: 654654228951.dkr.ecr.ap-southeast-1.amazonaws.com
---
bases:
  - ../../global.yaml
  - ../app.yaml

releases:
  - name: ddm-import
    installed: true
    namespace: ddm-import
    chart: ecr-uat-helm-charts/java
    version: 0.1.44568
    values:
      - default.values.yaml
      - {{ .Environment.Name }}.values.yaml
      - {{toYaml .Values | nindent 8}}
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "{{ .Environment.Name }}.secretClass.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"