image:
  repository:  654654228951.dkr.ecr.ap-southeast-1.amazonaws.com/ddm-import

extraEnvs:
  - name: PROPERTY_JDBC_HOST
    value: "prd-app-oracle-oracledb.cha4uqgeogfu.ap-southeast-1.rds.amazonaws.com"
  - name: PROPERTY_JDBC_URL
    value: "jdbc:oracle:thin:@$(PROPERTY_JDBC_HOST):1581/DDM"
  - name: PROPERTY_JDBC_USERNAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: username
  - name: PROPERTY_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets-manager-secret
        key: password
  - name: PROPERTY_HTTP_PORT
    value: "8181"
  - name: PROPERTY_LIODATAEXCHANGEPATH
    value: "/liodv/customer/LTA/exchange"
  - name: PROPERTY_LOGGEDIN_VEHICLE_URL
    value: ""
  - name: LOG_APPENDER
    value: "ConsoleAppender"
  - name: PROPERTY_DDM_STORAGE_PATH
    value: "/ddm/storage"
  - name: TEMPORARY_PATH
    value: "/ddm/importservice"
  - name: IMPORTSERVICE_INTERVAL
    value: "5"
  - name: TZ
    value: "Asia/Singapore"
  - name: PROPERTY_OTLP_COLLECTOR_URL
    value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  - name: PROPERTY_OTLP_IMPORT_SERVICE_NAME
    value: "DDM_IMPORT_SERVICE"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: NATS_SERVER
    value: "nats.fms.itfs.lta.gov.sg"
  - name: NATS_SUBJECT_ALERTS
    value: "DDM.Alerts.Alert"
  - name: ENVIRONMENT
    value: "prod"
  - name: DDM_MEMORY_THRESHOLD_MB
    value: "2000" 

serviceAccount:
  create: true
  name: ddm-import-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654228951:role/PRD-IAMR-EKS-APP-POD-IDENTITY-DDM

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: leader-election-role
      namespace: ddm-import
    rules:
      - apiGroups: ["coordination.k8s.io"]
        resources: ["leases"]
        verbs: ["get","list","watch","create","update","patch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-binding
      namespace: ddm-import
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: leader-election-role
    subjects:
      - kind: ServiceAccount
        name: ddm-import-sa
        namespace: ddm-import
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ddm-import-ddm-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: ddm-import-ddm-fsx-pv

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ddm-import-liodv-fsx-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
      volumeName: ddm-import-liodv-fsx-pv

extraVolumes:
  - name: fsx-data
    persistentVolumeClaim:
      claimName: ddm-import-ddm-fsx-pvc

  - name: fsx-liodataexchange
    persistentVolumeClaim:
      claimName: ddm-import-liodv-fsx-pvc

  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "ddm-import-spc"

extraVolumeMounts:
  - name: fsx-data
    mountPath: "/ddm"

  - name: fsx-liodataexchange
    mountPath: "/liodv"
  
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

ingress:
  enabled: true
  className: alb-internal-app
  annotations:
    kubernetes.io/tls-acme: "false"
    certmanager.k8s.io/cluster-issuer: acm-aws
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200,302"
    alb.ingress.kubernetes.io/load-balancer-name: prd-app-intra-eks-app-alb-eks
    alb.ingress.kubernetes.io/group.name: alb-internal-app
    alb.ingress.kubernetes.io/security-groups: sg-08b5165e42765ab7d
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-southeast-1:654654228951:regional/webacl/PRD-APP-INTRA-EKS-APP-WAF/2d40298d-b31c-4edf-b5ee-b6c9c928a17e
  hosts:
    - host: ddm-import.fms.itfs.lta.gov.sg
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - ddm-import.fms.itfs.lta.gov.sg
      secretName: ddm-import-tls

resources:
  limits:
    cpu: 512m
    memory: 2Gi
  requests:
    cpu: 128m
    memory: 1Gi
